# -*- coding: utf-8 -*-
"""clearance_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yKLpE8vpxAeoKWvKkkGPK6zREU_9RAxv
"""

import os
import numpy as np
import matplotlib.pyplot as plt

# ============================================================
# 1) USER INPUTS / CONSTANTS
# ============================================================

C_in = 0.1

# Configuration-specific membrane areas
# Computed from A_outer = 2*pi*Ro*L, with L = 20 mm
area_mm2_by_config = {
    "Inside-out": 31.42,
    "Outside-in": 21.36,
    "Adjusted outside-in": 198.23,
}

# Convert mm² -> m²
area_m2_by_config = {
    config: area_mm2 * 1e-6
    for config, area_mm2 in area_mm2_by_config.items()
}

T_min = 240
mps_to_uL_min_cm2 = 6e6

OUTPUT_DIR = "baseline_running_average_clearance_only"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ============================================================
# 2) FILE PATHS
# ============================================================

file_flux_IO_baseline = "totalnormalflux_IO_baseline_bm.txt"
file_flux_OI_baseline = "totalnormalflux_OI_baseline_bm.txt"
file_flux_OIadjusted_baseline = "totalnormalflux_OIadjusted_baseline_bm.txt"

# ============================================================
# 3) HELPER FUNCTIONS
# ============================================================

def cumulative_trapezoid_no_scipy(y, x):
    out = np.zeros_like(x, dtype=float)

    for i in range(1, len(x)):
        dx = x[i] - x[i - 1]
        out[i] = out[i - 1] + 0.5 * (y[i] + y[i - 1]) * dx

    return out


def load_two_column_file(filepath):
    data = np.loadtxt(filepath, comments="%")

    time_min = data[:, 0]
    values = data[:, 1]

    return time_min, values


def compute_running_average_clearance(time_min, flux_mol_s, config_name):

    time_sec = time_min * 60.0

    cumulative_flux_mol = cumulative_trapezoid_no_scipy(
        flux_mol_s,
        time_sec
    )

    CL_running_m_s = np.zeros_like(time_sec, dtype=float)

    nonzero = time_sec > 0

    # Use configuration-specific area
    A_m2 = area_m2_by_config[config_name]

    CL_running_m_s[nonzero] = cumulative_flux_mol[nonzero] / (
        time_sec[nonzero] * A_m2 * C_in
    )

    CL_running_uL_min_cm2 = np.abs(
        CL_running_m_s * mps_to_uL_min_cm2
    )

    return CL_running_uL_min_cm2


def restrict_to_240min(time_min, values):
    mask = time_min <= T_min
    return time_min[mask], values[mask]


def save_current_figure(filename):
    plt.tight_layout()

    plt.savefig(
        os.path.join(OUTPUT_DIR, filename),
        dpi=300
    )

    plt.show()

# ============================================================
# 4) LOAD FLUX DATA
# ============================================================

t_IO, flux_IO = load_two_column_file(file_flux_IO_baseline)
t_OI, flux_OI = load_two_column_file(file_flux_OI_baseline)
t_OIadj, flux_OIadj = load_two_column_file(
    file_flux_OIadjusted_baseline
)

t_IO, flux_IO = restrict_to_240min(t_IO, flux_IO)
t_OI, flux_OI = restrict_to_240min(t_OI, flux_OI)
t_OIadj, flux_OIadj = restrict_to_240min(
    t_OIadj,
    flux_OIadj
)

# ============================================================
# 5) COMPUTE RUNNING-AVERAGE CLEARANCE
# ============================================================

CLrun_IO = compute_running_average_clearance(
    t_IO,
    flux_IO,
    "Inside-out"
)

CLrun_OI = compute_running_average_clearance(
    t_OI,
    flux_OI,
    "Outside-in"
)

CLrun_OIadj = compute_running_average_clearance(
    t_OIadj,
    flux_OIadj,
    "Adjusted outside-in"
)

# ============================================================
# 6) STYLE SETTINGS
# ============================================================

colors = {
    "Inside-out": "tab:blue",
    "Outside-in": "tab:orange",
    "Adjusted outside-in": "tab:green",
}

markers = {
    "Inside-out": "o",
    "Outside-in": "s",
    "Adjusted outside-in": "^",
}

# ============================================================
# 7) PLOT: RUNNING TIME-AVERAGED CLEARANCE ONLY
# ============================================================

plt.figure(figsize=(8, 5.5))

plt.plot(
    t_IO,
    CLrun_IO,
    marker=markers["Inside-out"],
    linestyle="None",
    color=colors["Inside-out"],
    label=f"Inside-out "
)

plt.plot(
    t_OI,
    CLrun_OI,
    marker=markers["Outside-in"],
    linestyle="None",
    color=colors["Outside-in"],
    label=f"Outside-in "
)

plt.plot(
    t_OIadj,
    CLrun_OIadj,
    marker=markers["Adjusted outside-in"],
    linestyle="None",
    color=colors["Adjusted outside-in"],
    label=(
        f"Adjusted outside-in "
    )
)

# ============================================================
# 8) FORMATTING
# ============================================================

plt.xlabel("Time (min)")

plt.ylabel(
    "Running Time-Average Clearance "
    "(uL/(min·cm$^2$))"
)

plt.title(
    "Running Time-Averaged Clearance, Baseline Model"
)

plt.xlim(0, 240)

plt.grid(True, alpha=0.3)

plt.legend()

# ============================================================
# 9) SAVE FIGURE
# ============================================================

save_current_figure(
    "running_average_clearance_baseline_only.png"
)

# ============================================================
# 10) PRINT FINAL VALUES
# ============================================================

print("=" * 70)
print("FINAL RUNNING-AVERAGE CLEARANCE AT 240 MIN")
print("=" * 70)

print(
    f"Inside-out:           {CLrun_IO[-1]:.6e} uL/(min*cm^2) "
    f"| Area = {area_mm2_by_config['Inside-out']:.2f} mm^2"
)

print(
    f"Outside-in:           {CLrun_OI[-1]:.6e} uL/(min*cm^2) "
    f"| Area = {area_mm2_by_config['Outside-in']:.2f} mm^2"
)

print(
    f"Adjusted outside-in:  {CLrun_OIadj[-1]:.6e} uL/(min*cm^2) "
    f"| Area = "
    f"{area_mm2_by_config['Adjusted outside-in']:.2f} mm^2"
)

print()

import os
import numpy as np
import matplotlib.pyplot as plt

# ============================================================
# 1) USER INPUTS / CONSTANTS
# ============================================================

T_min = 240

# Conversion:
# mm/min -> uL/(min*cm^2)
# 1 mm = 0.1 cm
# 1 cm/min = 1000 uL/(min*cm^2)
# therefore 1 mm/min = 100 uL/(min*cm^2)
mm_per_min_to_uL_min_cm2 = 100

OUTPUT_DIR = "baseline_refoyo_definition_from_mm_plots"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ============================================================
# 2) FILE PATHS
# ============================================================

files = {
    "Inside-out": "Refoyodefinition_baselineinsideout_[mm].txt",
    "Outside-in": "refoyodefinition_OI_baseline_[mm].txt",
    "Adjusted outside-in": "refoyodefinition_adjustedOI_baseline_[mm].txt",
}

colors = {
    "Inside-out": "tab:blue",
    "Outside-in": "tab:orange",
    "Adjusted outside-in": "tab:green",
}

markers = {
    "Inside-out": "o",
    "Outside-in": "s",
    "Adjusted outside-in": "^",
}

# ============================================================
# 3) HELPER FUNCTIONS
# ============================================================

def load_two_column_file(filepath):
    data = np.loadtxt(filepath, comments="%")
    time_min = data[:, 0]
    refoyo_mm = data[:, 1]
    return time_min, refoyo_mm


def restrict_to_20_to_240min(time_min, values):
    mask = (time_min >= 20) & (time_min <= T_min)
    return time_min[mask], values[mask]


def compute_refoyo_clearance_from_mm(time_min, refoyo_mm):
    # Divide mm value by time in minutes
    clearance_mm_per_min = refoyo_mm / time_min

    # Convert mm/min to uL/(min*cm^2)
    clearance_uL_min_cm2 = clearance_mm_per_min * mm_per_min_to_uL_min_cm2

    return np.abs(clearance_uL_min_cm2)


def save_current_figure(filename):
    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, filename), dpi=300)
    plt.show()

# ============================================================
# 4) LOAD AND COMPUTE CLEARANCE
# ============================================================

clearance_by_config = {}
time_by_config = {}

for config_name, filepath in files.items():

    if not os.path.exists(filepath):
        raise FileNotFoundError(f"Missing file: {filepath}")

    time_min, refoyo_mm = load_two_column_file(filepath)

    # Exclude 0 min, keep 20-240 min
    time_min, refoyo_mm = restrict_to_20_to_240min(time_min, refoyo_mm)

    clearance = compute_refoyo_clearance_from_mm(time_min, refoyo_mm)

    time_by_config[config_name] = time_min
    clearance_by_config[config_name] = clearance

# ============================================================
# 5) PLOT ALL THREE CONFIGURATIONS
# ============================================================

plt.figure(figsize=(8.5, 5.5))

for config_name in files.keys():

    plt.plot(
        time_by_config[config_name],
        clearance_by_config[config_name],
        marker=markers[config_name],
        linestyle="None",
        color=colors[config_name],
        label=config_name,
        markersize=7,
    )

plt.xlabel("Time (min)")
plt.ylabel("Dialysate-based clearance (uL/(min·cm$^2$))")

plt.title(
    "Dialysate-based clearance (baseline model)"
)

plt.xlim(0, 240)
plt.grid(True, alpha=0.3)
plt.legend(title="Configuration")

save_current_figure("baseline_refoyo_clearance_from_mm_all_configurations.png")

# ============================================================
# 6) PRINT VALUES
# ============================================================

print("=" * 80)
print("Dialysate-based clearance (static conditions)")
print("0 min excluded; values from 20 to 240 min")
print("=" * 80)

for_config_order = [
    "Inside-out",
    "Outside-in",
    "Adjusted outside-in",
]

for config_name in for_config_order:

    print()
    print(config_name)
    print("-" * len(config_name))

    for t, cl in zip(
        time_by_config[config_name],
        clearance_by_config[config_name]
    ):
        print(
            f"{t:6.0f} min | "
            f"{cl:.6e} uL/(min*cm^2)"
        )

print()

import os
import numpy as np
import matplotlib.pyplot as plt

# ============================================================
# 1) USER INPUTS / CONSTANTS
# ============================================================

C_in = 0.1

# Configuration-specific membrane areas
# Computed from A_outer = 2*pi*Ro*L, with L = 20 mm
area_mm2_by_config = {
    "Inside-out": 31.42,
    "Outside-in": 21.36,
    "Adjusted outside-in": 198.23,
}

# Convert mm² -> m²
area_m2_by_config = {
    config: area_mm2 * 1e-6
    for config, area_mm2 in area_mm2_by_config.items()
}

T_min = 240
mps_to_uL_min_cm2 = 6e6

OUTPUT_DIR = "countercurrent_running_average_clearance_plot"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ============================================================
# 2) FILE PATHS (COUNTERCURRENT ONLY)
# ============================================================

file_flux_IO_counter = "totalnormalflux_IO_countercurrent_bm.txt"
file_flux_OI_counter = "totalnormalflux_OI_countercurrent_bm.txt"
file_flux_OIadj_counter = "totalnormalflux_OIadjusted_countercurrent_bm.txt"

# ============================================================
# 3) HELPER FUNCTIONS
# ============================================================

def cumulative_trapezoid_no_scipy(y, x):
    out = np.zeros_like(x, dtype=float)

    for i in range(1, len(x)):
        dx = x[i] - x[i - 1]
        out[i] = out[i - 1] + 0.5 * (y[i] + y[i - 1]) * dx

    return out


def load_flux_file(filepath):
    data = np.loadtxt(filepath, comments="%")

    time_min = data[:, 0]
    flux_mol_s = data[:, 1]

    return time_min, flux_mol_s


def restrict_to_240min(time_min, values):
    mask = time_min <= T_min
    return time_min[mask], values[mask]


def compute_running_average_clearance(time_min, flux_mol_s, config_name):
    time_sec = time_min * 60.0

    cumulative_flux_mol = cumulative_trapezoid_no_scipy(
        flux_mol_s,
        time_sec
    )

    CL_running_m_s = np.zeros_like(time_sec, dtype=float)
    nonzero = time_sec > 0

    # Use configuration-specific area
    A_m2 = area_m2_by_config[config_name]

    CL_running_m_s[nonzero] = cumulative_flux_mol[nonzero] / (
        time_sec[nonzero] * A_m2 * C_in
    )

    CL_running_uL_min_cm2 = np.abs(
        CL_running_m_s * mps_to_uL_min_cm2
    )

    return CL_running_uL_min_cm2


def save_current_figure(filename):
    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, filename), dpi=300)
    plt.show()

# ============================================================
# 4) LOAD DATA
# ============================================================

t_IO, flux_IO = load_flux_file(file_flux_IO_counter)
t_OI, flux_OI = load_flux_file(file_flux_OI_counter)
t_OIadj, flux_OIadj = load_flux_file(file_flux_OIadj_counter)

t_IO, flux_IO = restrict_to_240min(t_IO, flux_IO)
t_OI, flux_OI = restrict_to_240min(t_OI, flux_OI)
t_OIadj, flux_OIadj = restrict_to_240min(t_OIadj, flux_OIadj)

# ============================================================
# 5) COMPUTE RUNNING-AVERAGE CLEARANCE
# ============================================================

CLrun_IO = compute_running_average_clearance(
    t_IO,
    flux_IO,
    "Inside-out"
)

CLrun_OI = compute_running_average_clearance(
    t_OI,
    flux_OI,
    "Outside-in"
)

CLrun_OIadj = compute_running_average_clearance(
    t_OIadj,
    flux_OIadj,
    "Adjusted outside-in"
)

# ============================================================
# 6) STYLE SETTINGS
# ============================================================

colors = {
    "Inside-out": "tab:blue",
    "Outside-in": "tab:orange",
    "Adjusted outside-in": "tab:green",
}

markers = {
    "Inside-out": "o",
    "Outside-in": "s",
    "Adjusted outside-in": "^",
}

# ============================================================
# 7) PLOT (COUNTERCURRENT ONLY)
# ============================================================

plt.figure(figsize=(8.5, 5.5))

plt.plot(
    t_IO,
    CLrun_IO,
    marker=markers["Inside-out"],
    linestyle="None",
    color=colors["Inside-out"],
    label="Inside-out",
    markersize=7,
)

plt.plot(
    t_OI,
    CLrun_OI,
    marker=markers["Outside-in"],
    linestyle="None",
    color=colors["Outside-in"],
    label="Outside-in",
    markersize=7,
)

plt.plot(
    t_OIadj,
    CLrun_OIadj,
    marker=markers["Adjusted outside-in"],
    linestyle="None",
    color=colors["Adjusted outside-in"],
    label="Adjusted outside-in",
    markersize=7,
)

# ============================================================
# 8) FORMATTING
# ============================================================

plt.xlabel("Time (min)")
plt.ylabel("Running Time-Average Clearance (uL/(min·cm$^2$))")

plt.title(
    "Running Time-Averaged Clearance (Countercurrent Flow)\n"
    "Comparison of Configurations"
)

plt.xlim(0, 240)
plt.grid(True, alpha=0.3)

plt.legend(title="Configuration", frameon=False)

# ============================================================
# 9) SAVE FIGURE
# ============================================================

save_current_figure("running_average_clearance_countercurrent_only.png")

# ============================================================
# 10) PRINT FINAL VALUES
# ============================================================

print("=" * 70)
print("FINAL RUNNING-AVERAGE CLEARANCE AT 240 MIN (COUNTERCURRENT)")
print("=" * 70)

print(
    f"Inside-out:           {CLrun_IO[-1]:.6e} uL/(min*cm^2) "
    f"| Area = {area_mm2_by_config['Inside-out']:.2f} mm^2"
)

print(
    f"Outside-in:           {CLrun_OI[-1]:.6e} uL/(min*cm^2) "
    f"| Area = {area_mm2_by_config['Outside-in']:.2f} mm^2"
)

print(
    f"Adjusted outside-in:  {CLrun_OIadj[-1]:.6e} uL/(min*cm^2) "
    f"| Area = {area_mm2_by_config['Adjusted outside-in']:.2f} mm^2"
)

print()

import os
import numpy as np
import matplotlib.pyplot as plt

# ============================================================
# 1) USER INPUTS / CONSTANTS
# ============================================================

C_in = 0.1

# ------------------------------------------------------------
# Configuration-specific membrane areas
# Computed from:
# A_outer = 2*pi*Ro*L
# with L = 20 mm
# ------------------------------------------------------------

area_mm2_by_config = {
    "Inside-out": 31.42,
    "Outside-in": 21.36,
    "Adjusted outside-in": 198.23,
}

# Convert mm² -> m²
area_m2_by_config = {
    config: area_mm2 * 1e-6
    for config, area_mm2 in area_mm2_by_config.items()
}

mps_to_uL_min_cm2 = 6e6

OUTPUT_DIR = "model_derived_clearance_flow_comparison_plots"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ============================================================
# 2) FILE PATHS
# ============================================================

flow_cases = ["Baseline", "Countercurrent", "Cocurrent"]

config_files = {
    "Inside-out": {
        "Baseline": "totalnormalflux_IO_baseline_bm.txt",
        "Countercurrent": "totalnormalflux_IO_countercurrent_bm.txt",
        "Cocurrent": "totalnormalflux_IO_cocurrent_bm.txt",
    },
    "Outside-in": {
        "Baseline": "totalnormalflux_OI_baseline_bm.txt",
        "Countercurrent": "totalnormalflux_OI_countercurrent_bm.txt",
        "Cocurrent": "totalnormalflux_OI_cocurrent_bm.txt",
    },
    "Adjusted outside-in": {
        "Baseline": "totalnormalflux_OIadjusted_baseline_bm.txt",
        "Countercurrent": "totalnormalflux_OIadjusted_countercurrent_bm.txt",
        "Cocurrent": "totalnormalflux_OIadjusted_cocurrent_bm.txt",
    },
}

colors = {
    "Inside-out": "tab:blue",
    "Outside-in": "tab:orange",
    "Adjusted outside-in": "tab:green",
}

# ============================================================
# 3) HELPER FUNCTIONS
# ============================================================

def load_flux_file_auto_time(filepath):
    data = np.loadtxt(filepath, comments="%")

    time_raw = data[:, 0]
    flux_mol_s = data[:, 1]

    # If time looks like seconds, convert to minutes
    if time_raw[-1] > 1000:
        time_min = time_raw / 60.0
    else:
        time_min = time_raw

    return time_min, flux_mol_s


def compute_model_derived_clearance(filepath, config_name):
    time_min, flux_mol_s = load_flux_file_auto_time(filepath)

    time_sec = time_min * 60.0
    total_mol = np.trapz(flux_mol_s, time_sec)

    # Use configuration-specific area
    A_m2 = area_m2_by_config[config_name]

    CL_model_m_s = total_mol / (time_sec[-1] * A_m2 * C_in)
    CL_model_uL_min_cm2 = abs(CL_model_m_s * mps_to_uL_min_cm2)

    return CL_model_uL_min_cm2


def save_current_figure(filename):
    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, filename), dpi=300)
    plt.show()


def add_bar_labels(bars, values):
    max_value = max(values)

    for bar, value in zip(bars, values):
        plt.text(
            bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 0.02 * max_value,
            f"{value:.3e}",
            ha="center",
            va="bottom",
            fontsize=9,
            rotation=0,
        )

# ============================================================
# 4) COMPUTE MODEL-DERIVED CLEARANCE FOR ALL CASES
# ============================================================

clearance_by_config = {}

print("=" * 90)
print("MODEL-DERIVED CLEARANCE VALUES")
print("=" * 90)

for config_name, files_for_config in config_files.items():

    clearance_by_config[config_name] = {}

    print(
        f"{config_name:22s} | "
        f"Area = {area_mm2_by_config[config_name]:.2f} mm^2"
    )

    for flow_case in flow_cases:

        filepath = files_for_config[flow_case]

        if not os.path.exists(filepath):
            raise FileNotFoundError(
                f"Missing file for {config_name}, {flow_case}: {filepath}"
            )

        clearance = compute_model_derived_clearance(
            filepath,
            config_name
        )

        clearance_by_config[config_name][flow_case] = clearance

        print(
            f"{config_name:22s} | "
            f"{flow_case:14s} | "
            f"Model-derived clearance = "
            f"{clearance:.6e} uL/(min*cm^2)"
        )

print("=" * 90)

# ============================================================
# 5) GROUPED BAR PLOT
# ============================================================

plt.figure(figsize=(11, 6.5))

group_spacing = 1.25
x = np.arange(len(flow_cases)) * group_spacing
bar_width = 0.22

all_values = []

for i, config_name in enumerate(config_files.keys()):

    values = [
        clearance_by_config[config_name][flow_case]
        for flow_case in flow_cases
    ]

    all_values.extend(values)

    offset = (i - 1) * bar_width * 1.25

    bars = plt.bar(
        x + offset,
        values,
        width=bar_width,
        color=colors[config_name],
        label=config_name,
    )

    add_bar_labels(bars, values)

plt.ylim(0, max(all_values) * 1.25)
plt.xticks(x, flow_cases)

plt.xlabel("Flow condition")
plt.ylabel("Model-Derived Clearance (uL/(min·cm$^2$))")

plt.title(
    "Model-Derived Clearance for Different "
    "Flow Conditions and Configurations"
)

plt.grid(True, axis="y", alpha=0.3)
plt.legend(title="Configuration")

save_current_figure(
    "model_derived_clearance_flow_conditions_grouped.png"
)

# ============================================================
# 6) OPTIONAL: ONE BAR PLOT PER FLOW CONDITION
# ============================================================

for flow_case in flow_cases:

    plt.figure(figsize=(8.5, 5.8))

    labels = list(config_files.keys())

    values = [
        clearance_by_config[config_name][flow_case]
        for config_name in labels
    ]

    bars = plt.bar(
        labels,
        values,
        color=[colors[config_name] for config_name in labels],
        width=0.55,
    )

    add_bar_labels(bars, values)

    plt.ylim(0, max(values) * 1.25)

    plt.xlabel("Configuration")

    plt.ylabel(
        "Model-Derived Clearance Magnitude "
        "(uL/(min·cm$^2$))"
    )

    plt.title(f"Model-Derived Clearance, {flow_case}")

    plt.grid(True, axis="y", alpha=0.3)

    safe_flow = flow_case.lower().replace(" ", "_")

    save_current_figure(
        f"model_derived_clearance_{safe_flow}_configurations.png"
    )

import os
import numpy as np
import matplotlib.pyplot as plt

# ============================================================
# 1) USER INPUTS / CONSTANTS
# ============================================================

C_in = 0.1

# Conversion:
# m^3/s -> uL/min
m3s_to_uL_min = 60 * 1e9

OUTPUT_DIR = "model_derived_clearance_flow_comparison_plots_no_area_normalization"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ============================================================
# 2) FILE PATHS
# ============================================================

flow_cases = ["Baseline", "Countercurrent", "Cocurrent"]

config_files = {
    "Inside-out": {
        "Baseline": "totalnormalflux_IO_baseline_bm.txt",
        "Countercurrent": "totalnormalflux_IO_countercurrent_bm.txt",
        "Cocurrent": "totalnormalflux_IO_cocurrent_bm.txt",
    },
    "Outside-in": {
        "Baseline": "totalnormalflux_OI_baseline_bm.txt",
        "Countercurrent": "totalnormalflux_OI_countercurrent_bm.txt",
        "Cocurrent": "totalnormalflux_OI_cocurrent_bm.txt",
    },
    "Adjusted outside-in": {
        "Baseline": "totalnormalflux_OIadjusted_baseline_bm.txt",
        "Countercurrent": "totalnormalflux_OIadjusted_countercurrent_bm.txt",
        "Cocurrent": "totalnormalflux_OIadjusted_cocurrent_bm.txt",
    },
}

colors = {
    "Inside-out": "tab:blue",
    "Outside-in": "tab:orange",
    "Adjusted outside-in": "tab:green",
}

# ============================================================
# 3) HELPER FUNCTIONS
# ============================================================

def load_flux_file_auto_time(filepath):
    data = np.loadtxt(filepath, comments="%")

    time_raw = data[:, 0]
    flux_mol_s = data[:, 1]

    if time_raw[-1] > 1000:
        time_min = time_raw / 60.0
    else:
        time_min = time_raw

    return time_min, flux_mol_s


def compute_model_derived_clearance_no_area(filepath):
    time_min, flux_mol_s = load_flux_file_auto_time(filepath)

    time_sec = time_min * 60.0
    total_mol = np.trapz(flux_mol_s, time_sec)

    # No membrane area normalization
    # Average volumetric clearance:
    # CL = total transported amount / (time * inlet concentration)
    CL_model_m3_s = total_mol / (time_sec[-1] * C_in)

    CL_model_uL_min = abs(CL_model_m3_s * m3s_to_uL_min)

    return CL_model_uL_min


def save_current_figure(filename):
    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, filename), dpi=300)
    plt.show()


def add_bar_labels(bars, values):
    max_value = max(values)

    for bar, value in zip(bars, values):
        plt.text(
            bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 0.02 * max_value,
            f"{value:.3e}",
            ha="center",
            va="bottom",
            fontsize=9,
        )

# ============================================================
# 4) COMPUTE MODEL-DERIVED CLEARANCE FOR ALL CASES
# ============================================================

clearance_by_config = {}

print("=" * 90)
print("MODEL-DERIVED CLEARANCE VALUES WITHOUT AREA NORMALIZATION")
print("=" * 90)

for config_name, files_for_config in config_files.items():

    clearance_by_config[config_name] = {}

    for flow_case in flow_cases:

        filepath = files_for_config[flow_case]

        if not os.path.exists(filepath):
            raise FileNotFoundError(
                f"Missing file for {config_name}, {flow_case}: {filepath}"
            )

        clearance = compute_model_derived_clearance_no_area(filepath)

        clearance_by_config[config_name][flow_case] = clearance

        print(
            f"{config_name:22s} | "
            f"{flow_case:14s} | "
            f"Model-derived clearance = "
            f"{clearance:.6e} uL/min"
        )

print("=" * 90)

# ============================================================
# 5) GROUPED BAR PLOT
# ============================================================

plt.figure(figsize=(11, 6.5))

group_spacing = 1.25
x = np.arange(len(flow_cases)) * group_spacing
bar_width = 0.22

all_values = []

for i, config_name in enumerate(config_files.keys()):

    values = [
        clearance_by_config[config_name][flow_case]
        for flow_case in flow_cases
    ]

    all_values.extend(values)

    offset = (i - 1) * bar_width * 1.25

    bars = plt.bar(
        x + offset,
        values,
        width=bar_width,
        color=colors[config_name],
        label=config_name,
    )

    add_bar_labels(bars, values)

plt.ylim(0, max(all_values) * 1.25)
plt.xticks(x, flow_cases)

plt.xlabel("Flow condition")
plt.ylabel("Model-derived clearance (uL/min)")

plt.title(
    "Model-Derived Clearance Without Area Normalization\n"
    "for Different Flow Conditions and Configurations"
)

plt.grid(True, axis="y", alpha=0.3)
plt.legend(title="Configuration")

save_current_figure(
    "model_derived_clearance_no_area_grouped.png"
)

# ============================================================
# 6) OPTIONAL: ONE BAR PLOT PER FLOW CONDITION
# ============================================================

for flow_case in flow_cases:

    plt.figure(figsize=(8.5, 5.8))

    labels = list(config_files.keys())

    values = [
        clearance_by_config[config_name][flow_case]
        for config_name in labels
    ]

    bars = plt.bar(
        labels,
        values,
        color=[colors[config_name] for config_name in labels],
        width=0.55,
    )

    add_bar_labels(bars, values)

    plt.ylim(0, max(values) * 1.25)

    plt.xlabel("Configuration")
    plt.ylabel("Model-derived clearance (uL/min)")

    plt.title(
        f"Model-Derived Clearance Without Area Normalization, {flow_case}"
    )

    plt.grid(True, axis="y", alpha=0.3)

    safe_flow = flow_case.lower().replace(" ", "_")

    save_current_figure(
        f"model_derived_clearance_no_area_{safe_flow}_configurations.png"
    )

