# -*- coding: utf-8 -*-
"""flow_direction_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VfxNMxpxBwVyt9R3dwC0qFO65ZgigENx
"""

import numpy as np
import matplotlib.pyplot as plt

def read_comsol_file(file_path):
    arc = []
    conc = []

    with open(file_path, "r") as f:
        for line in f:
            if line.startswith("%") or line.strip() == "":
                continue

            parts = line.split()
            if len(parts) == 2:
                try:
                    x = float(parts[0])
                    y = float(parts[1])
                    arc.append(x)
                    conc.append(y)
                except ValueError:
                    continue

    arc = np.array(arc)
    conc = np.array(conc)

    # Keep only the first dataset if multiple datasets are stacked
    split_indices = np.where(np.diff(arc) < 0)[0]
    if len(split_indices) > 0:
        end = split_indices[0] + 1
        arc = arc[:end]
        conc = conc[:end]

    return arc, conc


def flip_curve(conc):
    return conc[::-1]


def interpolate_to_common_x(x1, y1, x2, y2):
    x_min = max(np.min(x1), np.min(x2))
    x_max = min(np.max(x1), np.max(x2))
    n_points = max(len(x1), len(x2))

    x_common = np.linspace(x_min, x_max, n_points)
    y1_common = np.interp(x_common, x1, y1)
    y2_common = np.interp(x_common, x2, y2)

    return x_common, y1_common, y2_common


# -----------------------------
# File paths
# -----------------------------
blood_co_file = "concentration_blood_cocurrent_insideout_longerz.txt"
dial_co_file = "concentration_dialysate_cocurrent_insideout_longerz.txt"
blood_counter_file = "concentration_blood_countercurrent_insideout_longerz.txt"
dial_counter_file = "concentration_dialysate_countercurrent_insideout_longerz.txt"


# -----------------------------
# Read files
# -----------------------------
arc_blood_co, conc_blood_co = read_comsol_file(blood_co_file)
arc_dial_co, conc_dial_co = read_comsol_file(dial_co_file)

arc_blood_counter, conc_blood_counter = read_comsol_file(blood_counter_file)
arc_dial_counter, conc_dial_counter = read_comsol_file(dial_counter_file)


# -----------------------------
# Flip all four curves
# -----------------------------
conc_blood_co = flip_curve(conc_blood_co)
conc_dial_co = flip_curve(conc_dial_co)

conc_blood_counter = flip_curve(conc_blood_counter)
conc_dial_counter = flip_curve(conc_dial_counter)


# -----------------------------
# Plot 1: Co-current concentrations
# -----------------------------
plt.figure(figsize=(8, 5))
plt.plot(arc_blood_co, conc_blood_co, color="red", linewidth=2, label="Blood")
plt.plot(arc_dial_co, conc_dial_co, color="blue", linewidth=2, label="Dialysate")
plt.xlabel("Axial length (mm)")
plt.ylabel("Molar concentration, is (mol/m$^3$)")
plt.title("Co-current Flow: Blood vs Dialysate")
plt.grid(True, alpha=0.3)
plt.legend()
plt.tight_layout()
plt.show()


# -----------------------------
# Plot 2: Countercurrent concentrations
# -----------------------------
plt.figure(figsize=(8, 5))
plt.plot(arc_blood_counter, conc_blood_counter, color="red", linewidth=2, label="Blood")
plt.plot(arc_dial_counter, conc_dial_counter, color="blue", linewidth=2, label="Dialysate")
plt.xlabel("Axial length (mm)")
plt.ylabel("Molar concentration, is (mol/m$^3$)")
plt.title("Countercurrent Flow: Blood vs Dialysate")
plt.grid(True, alpha=0.3)
plt.legend()
plt.tight_layout()
plt.show()


# -----------------------------
# Difference curves
# -----------------------------
x_co, blood_co_i, dial_co_i = interpolate_to_common_x(
    arc_blood_co, conc_blood_co, arc_dial_co, conc_dial_co
)
diff_co = np.abs(blood_co_i - dial_co_i)

x_counter, blood_counter_i, dial_counter_i = interpolate_to_common_x(
    arc_blood_counter, conc_blood_counter, arc_dial_counter, conc_dial_counter
)
diff_counter = np.abs(blood_counter_i - dial_counter_i)


# -----------------------------
# Plot 3: Difference comparison
# -----------------------------
plt.figure(figsize=(9, 5))
plt.plot(x_co, diff_co, color="green", linewidth=2, label="Co-current |Blood - Dialysate|")
plt.plot(x_counter, diff_counter, color="purple", linewidth=2, label="Countercurrent |Blood - Dialysate|")

plt.fill_between(x_co, diff_co, alpha=0.15, color="green")
plt.fill_between(x_counter, diff_counter, alpha=0.15, color="purple")

plt.xlabel("Axial length (mm)")
plt.ylabel("|Blood - Dialysate| (mol/m$^3$)")
plt.title("Concentration Difference Along Axial Length")
plt.grid(True, alpha=0.3)
plt.legend()
plt.tight_layout()
plt.show()


# -----------------------------
# Quantify which one is larger
# -----------------------------
area_co = np.trapz(diff_co, x_co)
area_counter = np.trapz(diff_counter, x_counter)

max_diff_co = np.max(diff_co)
max_diff_counter = np.max(diff_counter)

if area_co > area_counter:
    larger_overall = "Co-current"
else:
    larger_overall = "Countercurrent"

if max_diff_co > max_diff_counter:
    larger_peak = "Co-current"
else:
    larger_peak = "Countercurrent"

print("Integrated difference over axial length:")
print(f"  Co-current     = {area_co:.6f}")
print(f"  Countercurrent = {area_counter:.6f}")
print(f"  Larger overall difference = {larger_overall}")

print("\nMaximum pointwise difference:")
print(f"  Co-current     = {max_diff_co:.6f}")
print(f"  Countercurrent = {max_diff_counter:.6f}")
print(f"  Larger peak difference = {larger_peak}")

