# -*- coding: utf-8 -*-
"""mesh_sensitivity_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DnlqK02STevuv0RZJMg_vMSx-GV_Fwnt
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
from matplotlib.ticker import FormatStrFormatter

# ==================================================
# SETTINGS
# ==================================================

threshold = 0.02  # ±2% in fractional form

# ----------------------------
# Blood-to-membrane flux
# ----------------------------
bm_files = [f"MSA_hor_{i}_bm.txt" for i in range(1, 8)]
bm_reference_file = "MSA_reference_bm.txt"
bm_times_to_keep = [0.5, 1, 1.5, 2.5, 6, 10]

# ----------------------------
# Membrane-to-cell flux
# ----------------------------
mc_files = [f"MSA_hor_{i}_mc.txt" for i in range(1, 8)]
mc_reference_file = "MSA_reference_mc.txt"
mc_times_to_keep = [0.5, 1, 1.5, 2.5, 6, 10]

# ----------------------------
# Cell-to-dialysate flux
# ----------------------------
cd_files = [f"MSA_hor_{i}_cd.txt" for i in range(1, 8)]
cd_reference_file = "MSA_reference_cd.txt"
cd_times_to_keep = [0.5, 1, 1.5, 2.5, 6, 10]

# ----------------------------
# Probe points
# ----------------------------
is_files = [f"MSA_hor_{i}_is.txt" for i in range(1, 8)]
is_reference_file = "MSA_reference_is.txt"
is_times_to_keep = [0.5, 1, 1.5, 2.5, 6, 10]
is_time_col = "Time (min)"

# x-axis labels
x_labels = [
    "50 vs 400",
    "100 vs 400",
    "150 vs 400",
    "200 vs 400",
    "250 vs 400",
    "300 vs 400",
    "350 vs 400",
]

# ==================================================
# READERS
# ==================================================

def read_comsol_single_flux_table(filepath):
    """
    Reads COMSOL text export with:
    Time (min) + 1 flux column

    Returns dataframe with columns:
    ['Time (min)', 'Flux']
    """
    data = []

    with open(filepath, "r", encoding="utf-8") as f:
        for line in f:
            stripped = line.strip()

            if not stripped or stripped.startswith("%"):
                continue

            values = [float(x) for x in stripped.split()]
            data.append(values)

    if len(data) == 0:
        raise ValueError(f"No numeric data found in {filepath}")

    ncols = len(data[0])
    if ncols != 2:
        raise ValueError(f"{filepath} should have 2 columns, found {ncols}")

    df = pd.DataFrame(data, columns=["Time (min)", "Flux"])
    return df


def read_comsol_probe_table(filepath):
    with open(filepath, "r", encoding="utf-8") as f:
        lines = f.readlines()

    header_line = None
    data_lines = []

    for line in lines:
        stripped = line.strip()

        if stripped.startswith("%"):
            if "Time (min)" in stripped:
                header_line = stripped.lstrip("%").strip()
        else:
            if stripped:
                data_lines.append(stripped)

    if header_line is None:
        raise ValueError(f"Could not find header line in {filepath}")

    pattern = r"(Time \(min\)|Molar concentration, is \(mol/m\^3\), Point: \([^)]+\))"
    columns = re.findall(pattern, header_line)

    seen = {}
    unique_columns = []
    for col in columns:
        if col not in seen:
            seen[col] = 0
            unique_columns.append(col)
        else:
            seen[col] += 1
            unique_columns.append(f"{col}__dup{seen[col]}")

    data = []
    for line in data_lines:
        values = [float(x) for x in line.split()]
        if len(values) == len(unique_columns):
            data.append(values)

    df = pd.DataFrame(data, columns=unique_columns)
    return df


# ==================================================
# HELPERS
# ==================================================

def extract_point(colname):
    clean_col = colname.split("__dup")[0]
    match = re.search(r"Point:\s*(\([^)]+\))", clean_col)
    return match.group(1) if match else "Unknown"


def filter_times(df, requested_times, time_column, tol=1e-9):
    rows = []
    for t in requested_times:
        matches = np.isclose(df[time_column], t, atol=tol)
        idx = np.where(matches)[0]
        if len(idx) == 0:
            raise ValueError(f"Time {t} not found in {time_column}")
        rows.append(df.iloc[idx[0]])

    out = pd.DataFrame(rows).reset_index(drop=True)
    out[time_column] = requested_times
    return out


def load_flux_series(filepath, requested_times):
    df = read_comsol_single_flux_table(filepath)
    df = filter_times(df, requested_times, "Time (min)")
    return df["Flux"].to_numpy()


def compute_relative_differences(reference_values, comparison_values):
    return np.where(
        np.isclose(reference_values, 0, atol=1e-30),
        np.nan,
        (reference_values - comparison_values) / reference_values
    )


def plot_flux_group(files, reference_file, times_to_keep, title):
    """
    Compare files with a single-flux reference file and plot:
    one figure, one curve per selected time
    """
    all_data = {}

    for fname in files:
        values = load_flux_series(fname, times_to_keep)
        all_data[fname] = values

    ref_values = load_flux_series(reference_file, times_to_keep)

    rel_diff = {}
    for fname in files:
        rel_diff[fname] = compute_relative_differences(ref_values, all_data[fname])

    x = np.arange(1, len(files) + 1)
    diff_matrix = np.array([rel_diff[f] for f in files])   # shape: (nfiles, ntimes)
    diff_percent = 100 * diff_matrix

    plt.figure(figsize=(11, 5))

    for t_idx, t in enumerate(times_to_keep):
        plt.plot(
            x,
            diff_percent[:, t_idx],
            marker="o",
            linewidth=2,
            label=f"{t} min"
        )

    plt.xticks(x, x_labels, rotation=20)
    plt.xlabel("Mesh comparison")
    plt.ylabel("Percentual difference (%)")
    plt.title(title)

    data_min = np.nanmin(diff_percent)
    data_max = np.nanmax(diff_percent)
    data_range = data_max - data_min

    if not np.isfinite(data_range) or data_range == 0:
        margin = 0.001
    else:
        margin = 0.2 * data_range

    plt.ylim(data_min - margin, data_max + margin)
    plt.gca().yaxis.set_major_formatter(FormatStrFormatter('%.4f'))

    plt.axhline(100 * threshold, color="red", linestyle="--", linewidth=1.5, label="±2% threshold")
    plt.axhline(-100 * threshold, color="red", linestyle="--", linewidth=1.5)

    plt.grid(True, linestyle="--", alpha=0.6)
    plt.legend()
    plt.tight_layout()
    plt.show()

    # Optional debug print
    print("\n============================================================")
    print(title)
    print(f"Reference file: {reference_file}")
    print("Formula       : (r - a) / r")
    print("Times kept    :", times_to_keep)
    print("============================================================")

    for fname in files:
        print(f"\nComparing {fname} to {reference_file}")
        a_vals = all_data[fname]

        for t, a, r in zip(times_to_keep, a_vals, ref_values):
            diff = (r - a) / r if abs(r) > 0 else np.nan
            print(
                f"t={t:>4} min | "
                f"a={a:.17e} | "
                f"r={r:.17e} | "
                f"(r-a)/r={diff:.17e}"
            )


def plot_probe_group(files, reference_file, times_to_keep, time_col):
    """
    Compare probe-point files with the probe reference file.
    One figure per probe point, one curve per selected time.
    """
    all_data = {}

    for fname in files:
        df = read_comsol_probe_table(fname)
        df = filter_times(df, times_to_keep, time_col)
        all_data[fname] = df

    ref_df = read_comsol_probe_table(reference_file)
    ref_df = filter_times(ref_df, times_to_keep, time_col)

    molar_cols = [c for c in ref_df.columns if c != time_col]

    relative_diff = {}
    for fname in files:
        relative_diff[fname] = {}
        for col in molar_cols:
            r = ref_df[col].to_numpy()
            a = all_data[fname][col].to_numpy()
            relative_diff[fname][col] = compute_relative_differences(r, a)

    x = np.arange(1, len(files) + 1)

    for col in molar_cols:
        point = extract_point(col)

        diff_matrix = np.array([
            relative_diff[f][col] for f in files
        ])
        diff_percent = 100 * diff_matrix

        plt.figure(figsize=(10, 5))

        for t_idx, t in enumerate(times_to_keep):
            plt.plot(
                x,
                diff_percent[:, t_idx],
                marker="o",
                linewidth=2,
                label=f"{t} min"
            )

        plt.xticks(x, x_labels, rotation=20)
        plt.xlabel("Mesh comparison")
        plt.ylabel("Percentual difference (%)")
        plt.title(f"Percentual difference at {point}")

        data_min = np.nanmin(diff_percent)
        data_max = np.nanmax(diff_percent)
        data_range = data_max - data_min

        if not np.isfinite(data_range) or data_range == 0:
            margin = 0.001
        else:
            margin = 0.2 * data_range

        plt.ylim(data_min - margin, data_max + margin)
        plt.gca().yaxis.set_major_formatter(FormatStrFormatter('%.4f'))

        plt.axhline(100 * threshold, color="red", linestyle="--", linewidth=1.5, label="±2% threshold")
        plt.axhline(-100 * threshold, color="red", linestyle="--", linewidth=1.5)

        plt.grid(True, linestyle="--", alpha=0.6)
        plt.legend()
        plt.tight_layout()
        from matplotlib.ticker import ScalarFormatter

        ax = plt.gca()

        formatter = ScalarFormatter(useMathText=True)
        formatter.set_scientific(True)
        formatter.set_powerlimits((-2, 2))  # force scientific notation

        ax.yaxis.set_major_formatter(formatter)
        plt.show()


# ==================================================
# RUN ALL COMPARISONS
# ==================================================

plot_flux_group(
    files=bm_files,
    reference_file=bm_reference_file,
    times_to_keep=bm_times_to_keep,
    title="Percentual difference for blood to membrane flux"
)

plot_flux_group(
    files=mc_files,
    reference_file=mc_reference_file,
    times_to_keep=mc_times_to_keep,
    title="Percentual difference for membrane to cell flux"
)

plot_flux_group(
    files=cd_files,
    reference_file=cd_reference_file,
    times_to_keep=cd_times_to_keep,
    title="Percentual difference for cell to dialysate flux"
)

plot_probe_group(
    files=is_files,
    reference_file=is_reference_file,
    times_to_keep=is_times_to_keep,
    time_col=is_time_col
)

