# -*- coding: utf-8 -*-
"""MM_transport_contribution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wTpEApMgXehNCzvSOxXMniWn6Wl0MvGB
"""

import pandas as pd
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt

data_dir = Path(".")

cases = [
    #("IO", "baseline"),
    ("IO", "countercurrent"),
    # ("OI", "baseline"),  # ignored
    ("OI", "countercurrent"),
    #("adjustedOI", "baseline"),
    ("adjustedOI", "countercurrent"),
]

def read_comsol_flux_file(file_path):
    df = pd.read_csv(
        file_path,
        comment="%",
        sep=r"\s+",
        header=None,
        names=["time_min", "flux"]
    )
    return df

plt.figure(figsize=(9, 6))

for geom, flow in cases:

    full_file = data_dir / f"totalnormalflux_{geom}_{flow}_cd_full.txt"
    vmax0_file = data_dir / f"totalnormalflux_{geom}_{flow}_cd_Vmax=0.txt"

    df_full = read_comsol_flux_file(full_file)
    df_vmax0 = read_comsol_flux_file(vmax0_file)

    df = pd.merge(
        df_full,
        df_vmax0,
        on="time_min",
        suffixes=("_full", "_Vmax0")
    )

    # Direction-independent ratio: Vmax=0 / full
    df["flux_ratio"] = (
        np.abs(df["flux_Vmax0"]) / np.abs(df["flux_full"])
    )

    label = f"{geom} - {flow}"

    plt.plot(
        df["time_min"],
        df["flux_ratio"],
        marker="o",
        linewidth=2,
        label=label
    )

plt.axhline(1, linestyle="--")

plt.xlabel("Time [min]")
plt.ylabel(r"$|\Phi_{\mathrm{Vmax=0}}| / |\Phi_{\mathrm{full}}|$")
plt.title("Vmax=1e6: flux ratio Vmax=0 relative to full model")
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt

data_dir = Path(".")

cases = [
    "IO",
    "OI",
    "adjustedOI",
]

def read_comsol_flux_file(file_path):
    df = pd.read_csv(
        file_path,
        comment="%",
        sep=r"\s+",
        header=None,
        names=["time_min", "flux"]
    )
    return df

plt.figure(figsize=(9, 6))

for geom in cases:

    full_file = data_dir / f"totalnormalflux_{geom}_countercurrent_Vmax1e9_full.txt"
    vmax0_file = data_dir / f"totalnormalflux_{geom}_countercurrent_Vmax1e9_vmax=0.txt"

    df_full = read_comsol_flux_file(full_file)
    df_vmax0 = read_comsol_flux_file(vmax0_file)

    df = pd.merge(
        df_full,
        df_vmax0,
        on="time_min",
        suffixes=("_full", "_Vmax0")
    )

    df["flux_ratio"] = (
        np.abs(df["flux_Vmax0"]) / np.abs(df["flux_full"])
    )

    # get value closest to 25 min
    row_25 = df.iloc[(df["time_min"] - 25).abs().argsort()[:1]]

    y_25 = row_25["flux_ratio"].values[0]

    print(f"{geom}: flux ratio at 25 min = {y_25:.4f}")

    label = f"{geom} - countercurrent"

    plt.plot(
        df["time_min"],
        df["flux_ratio"],
        marker="o",
        linewidth=2,
        label=label
    )
plt.axhline(1, linestyle="--")

plt.xlabel("Time [min]")
plt.ylabel(r"$|\Phi_{\mathrm{Vmax=0}}| / |\Phi_{\mathrm{full}}|$")
plt.title("Vmax=1e9: flux ratio Vmax=0 relative to full model")
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

