# -*- coding: utf-8 -*-
"""MSA_multifiber.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AAh9XSkR-jng7i_m5i4n3EGyyjPL1PKt
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
from matplotlib.ticker import ScalarFormatter

threshold = 0.02

io_files = [f"msa_multifibre_IO_{i}.txt" for i in range(1, 8)]
io_reference_file = "msa_multifibre_IO_8.txt"

oi_files = [f"msa_multifibre_OI_{i}.txt" for i in range(1, 8)]
oi_reference_file = "msa_multifibre_OI_8.txt"

times_to_keep = [20,60,100,140,180,220]
time_col = "Time (min)"

io_x_labels = [
    "100k vs 800k", "200k vs 800k", "300k vs 800k",
    "400k vs 800k", "500k vs 800k", "600k vs 800k",
    "700k vs 800k"
]

oi_x_labels = [
    "100k vs 800k", "200k vs 800k", "300k vs 800k",
    "400k vs 800k", "500k vs 800k", "600k vs 800k",
    "700k vs 800k"
]


def read_comsol_probe_table(filepath):
    with open(filepath, "r", encoding="utf-8") as f:
        lines = f.readlines()

    header_line = None
    data_lines = []

    for line in lines:
        stripped = line.strip()

        if stripped.startswith("%"):
            if "Time (min)" in stripped:
                header_line = stripped.lstrip("%").strip()
        else:
            if stripped:
                data_lines.append(stripped)

    if header_line is None:
        raise ValueError(f"Could not find header line in {filepath}")

    pattern = r"(Time \(min\)|Molar concentration, is \(mol/m\^3\), Point: \([^)]+\))"
    columns = re.findall(pattern, header_line)

    seen = {}
    unique_columns = []
    for col in columns:
        if col not in seen:
            seen[col] = 0
            unique_columns.append(col)
        else:
            seen[col] += 1
            unique_columns.append(f"{col}__dup{seen[col]}")

    data = []
    for line in data_lines:
        values = [float(x) for x in line.split()]
        if len(values) == len(unique_columns):
            data.append(values)

    return pd.DataFrame(data, columns=unique_columns)


def extract_point(colname):
    clean_col = colname.split("__dup")[0]
    match = re.search(r"Point:\s*(\([^)]+\))", clean_col)
    return match.group(1) if match else "Unknown"


def filter_times(df, requested_times, time_column, tol=1e-9):
    rows = []

    for t in requested_times:
        matches = np.isclose(df[time_column], t, atol=tol)
        idx = np.where(matches)[0]

        if len(idx) == 0:
            raise ValueError(f"Time {t} not found in {time_column}")

        rows.append(df.iloc[idx[0]])

    out = pd.DataFrame(rows).reset_index(drop=True)
    out[time_column] = requested_times
    return out


def compute_relative_differences(reference_values, comparison_values):
    return np.where(
        np.isclose(reference_values, 0, atol=1e-30),
        np.nan,
        (reference_values - comparison_values) / reference_values
    )


def plot_group(files, reference_file, times_to_keep, time_col, x_labels, group_name):
    all_data = {}

    for fname in files:
        df = read_comsol_probe_table(fname)
        df = filter_times(df, times_to_keep, time_col)
        all_data[fname] = df

    ref_df = read_comsol_probe_table(reference_file)
    ref_df = filter_times(ref_df, times_to_keep, time_col)

    molar_cols = [c for c in ref_df.columns if c != time_col]

    relative_diff = {}

    for fname in files:
        relative_diff[fname] = {}

        for col in molar_cols:
            r = ref_df[col].to_numpy()
            a = all_data[fname][col].to_numpy()
            relative_diff[fname][col] = compute_relative_differences(r, a)

    x = np.arange(1, len(files) + 1)

    for col in molar_cols:
        point = extract_point(col)

        diff_matrix = np.array([relative_diff[f][col] for f in files])
        diff_percent = 100 * diff_matrix

        plt.figure(figsize=(10, 5))

        for t_idx, t in enumerate(times_to_keep):
            plt.plot(
                x,
                diff_percent[:, t_idx],
                marker="o",
                linewidth=2,
                label=f"{t} min"
            )

        plt.xticks(x, x_labels, rotation=20)
        plt.xlabel("Mesh comparison")
        plt.ylabel("Percentual difference (%)")
        plt.title(f"{group_name}: Percentual difference at {point}")

        data_min = np.nanmin(diff_percent)
        data_max = np.nanmax(diff_percent)
        data_range = data_max - data_min

        margin = 0.001 if (not np.isfinite(data_range) or data_range == 0) else 0.2 * data_range
        plt.ylim(data_min - margin, data_max + margin)

        plt.axhline(100 * threshold, color="red", linestyle="--", linewidth=1.5, label="±2% threshold")
        plt.axhline(-100 * threshold, color="red", linestyle="--", linewidth=1.5)

        plt.grid(True, linestyle="--", alpha=0.6)
        plt.legend()
        plt.tight_layout()

        ax = plt.gca()
        formatter = ScalarFormatter(useMathText=True)
        formatter.set_scientific(True)
        formatter.set_powerlimits((-2, 2))
        ax.yaxis.set_major_formatter(formatter)

        plt.show()


plot_group(
    files=io_files,
    reference_file=io_reference_file,
    times_to_keep=times_to_keep,
    time_col=time_col,
    x_labels=io_x_labels,
    group_name="IO"
)

plot_group(
    files=oi_files,
    reference_file=oi_reference_file,
    times_to_keep=times_to_keep,
    time_col=time_col,
    x_labels=oi_x_labels,
    group_name="OI"
)

