# -*- coding: utf-8 -*-
"""multifiber_clearance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hOmVZAgaL9HJrQQPVTl-TbAG_5tXrkhL
"""

import os
import numpy as np
import matplotlib.pyplot as plt

# ============================================================
# 1) USER INPUTS / CONSTANTS
# ============================================================

C_in = 0.1
T_min = 240
mps_to_uL_min_cm2 = 6e6

OUTPUT_DIR = "combined_IO_OI_model_derived_clearance_plots"
os.makedirs(OUTPUT_DIR, exist_ok=True)

setups = {
    "Inside-out": {
        "A_mm2": 31.42,
        "color": "tab:blue",
        "files": {
            "Fiber 1": "totalnormalflux_IO_multifibre_countercurrent_240mins_fiber1.txt",
            "Fiber 2": "totalnormalflux_IO_multifibre_countercurrent_240mins_fiber2.txt",
            "Fiber 3": "totalnormalflux_IO_multifibre_countercurrent_240mins_fiber3.txt",
            "Fiber 4": "totalnormalflux_IO_multifibre_countercurrent_240mins_fiber4.txt",
            "Fiber 5": "totalnormalflux_IO_multifibre_countercurrent_240mins_fiber5.txt",
        },
    },
    "Outside-in": {
        "A_mm2": 21.36,
        "color": "tab:orange",
        "files": {
            "Fiber 1": "totalnormalflux_OI_multifibre_countercurrent_240mins_fiber1.txt",
            "Fiber 2": "totalnormalflux_OI_multifibre_countercurrent_240mins_fiber2.txt",
            "Fiber 3": "totalnormalflux_OI_multifibre_countercurrent_240mins_fiber3.txt",
            "Fiber 4": "totalnormalflux_OI_multifibre_countercurrent_240mins_fiber4.txt",
            "Fiber 5": "totalnormalflux_OI_multifibre_countercurrent_240mins_fiber5.txt",
        },
    },
}

# ============================================================
# 2) HELPER FUNCTIONS
# ============================================================

def cumulative_trapezoid_no_scipy(y, x):
    out = np.zeros_like(x, dtype=float)

    for i in range(1, len(x)):
        dx = x[i] - x[i - 1]
        out[i] = out[i - 1] + 0.5 * (y[i] + y[i - 1]) * dx

    return out


def load_two_column_file(filepath):
    data = np.loadtxt(filepath, comments="%")
    time_min = data[:, 0]
    flux_mol_s = data[:, 1]
    return time_min, flux_mol_s


def restrict_to_240min(time_min, values):
    mask = time_min <= T_min
    return time_min[mask], values[mask]


def compute_running_average_clearance(time_min, flux_mol_s, A_m2):
    time_sec = time_min * 60.0
    cumulative_flux_mol = cumulative_trapezoid_no_scipy(flux_mol_s, time_sec)

    CL_running_m_s = np.zeros_like(time_sec, dtype=float)
    nonzero = time_sec > 0

    CL_running_m_s[nonzero] = cumulative_flux_mol[nonzero] / (
        time_sec[nonzero] * A_m2 * C_in
    )

    return np.abs(CL_running_m_s * mps_to_uL_min_cm2)


def save_current_figure(filename):
    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, filename), dpi=300)
    plt.show()


# ============================================================
# 3) COMPUTE CLEARANCE VALUES FOR BOTH SETUPS
# ============================================================

clearance_240_values = {}

for setup_name, setup_info in setups.items():
    A_m2 = setup_info["A_mm2"] * 1e-6
    clearance_240_values[setup_name] = {}

    for fiber_label, file_path in setup_info["files"].items():
        time_min, flux_mol_s = load_two_column_file(file_path)
        time_min, flux_mol_s = restrict_to_240min(time_min, flux_mol_s)

        CL_running = compute_running_average_clearance(time_min, flux_mol_s, A_m2)
        CL_240 = CL_running[-1]

        clearance_240_values[setup_name][fiber_label] = CL_240


# ============================================================
# 4) PLOT 1: EACH FIBER, INSIDE-OUT AND OUTSIDE-IN TOGETHER
# ============================================================

fiber_labels = list(setups["Inside-out"]["files"].keys())
x = np.arange(len(fiber_labels))
bar_width = 0.38

plt.figure(figsize=(9, 5.5))

for i, setup_name in enumerate(setups.keys()):
    values = [clearance_240_values[setup_name][fiber] for fiber in fiber_labels]
    offset = (i - 0.5) * bar_width

    bars = plt.bar(
        x + offset,
        values,
        width=bar_width,
        color=setups[setup_name]["color"],
        edgecolor="black",
        label=setup_name,
    )

    if setup_name == "Inside-out":
        label_x_shift = -0.045
    else:
        label_x_shift = 0.045

    for bar, value in zip(bars, values):
        plt.text(
            bar.get_x() + bar.get_width() / 2 + label_x_shift,
            bar.get_height(),
            f"{value:.3e}",
            ha="center",
            va="bottom",
            fontsize=8,
        )

plt.xticks(x, fiber_labels)
plt.ylabel("End point time-average clearance at 240 min\n(uL/(min·cm$^2$))")
plt.title(
    "End point time-average clearance at 240 min for each fiber\n"
    "Multifibre countercurrent setup"
)
plt.legend()
plt.grid(axis="y", linestyle="--", alpha=0.6)

save_current_figure(
    "model_derived_clearance_240min_each_fiber_IO_vs_OI.png"
)


# ============================================================
# 5) PLOT 2: TOTAL CLEARANCE, INSIDE-OUT AND OUTSIDE-IN TOGETHER
# ============================================================

total_clearance_values = {
    setup_name: sum(clearance_240_values[setup_name].values())
    for setup_name in setups.keys()
}

plt.figure(figsize=(6.8, 5.5))

setup_names = list(total_clearance_values.keys())
total_values = list(total_clearance_values.values())
colors = [setups[name]["color"] for name in setup_names]

bars = plt.bar(
    setup_names,
    total_values,
    color=colors,
    edgecolor="black",
)

for bar, value in zip(bars, total_values):
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height(),
        f"{value:.3e}",
        ha="center",
        va="bottom",
        fontsize=10,
    )

plt.ylabel("End point time-average clearance at 240 min \n(uL/(min·cm$^2$))")
plt.xlabel("Setup")
plt.title(
    "End point time-average clearance at 240 min for multifibre countercurrent setup"
)

plt.legend(
    handles=[
        plt.Rectangle((0, 0), 1, 1, color=setups["Inside-out"]["color"], ec="black", label="Inside-out"),
        plt.Rectangle((0, 0), 1, 1, color=setups["Outside-in"]["color"], ec="black", label="Outside-in"),
    ]
)

plt.grid(axis="y", linestyle="--", alpha=0.6)

save_current_figure(
    "total_model_derived_clearance_240min_IO_vs_OI.png"
)


# ============================================================
# 6) PRINT FINAL VALUES
# ============================================================

print("=" * 80)
print("MODEL-DERIVED CLEARANCE AT 240 MIN")
print("INSIDE-OUT VS OUTSIDE-IN MULTIFIBRE COUNTERCURRENT SETUP")
print("=" * 80)

for setup_name in setups.keys():
    print(f"\n{setup_name.upper()}")
    print("-" * 80)
    print(f"A = {setups[setup_name]['A_mm2']:.6e} mm^2")
    print(f"A = {setups[setup_name]['A_mm2'] * 1e-6:.6e} m^2")

    for fiber_label, CL_240 in clearance_240_values[setup_name].items():
        print(f"{fiber_label}: {CL_240:.6e} uL/(min*cm^2)")

    print(
        f"Total: {total_clearance_values[setup_name]:.6e} uL/(min*cm^2)"
    )

print("=" * 80)

