# -*- coding: utf-8 -*-
"""parameter_sensitivity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10cVHyaF1_PiSi7sm1xSPnV6KMuzDZiBs
"""

import os
import numpy as np
import matplotlib.pyplot as plt

# ============================================================
# 1) USER INPUTS / CONSTANTS
# ============================================================

C_in = 0.1

area_mm2_by_config = {
    "Inside-out": 31.42,
    "Outside-in": 21.36,
    "Adjusted outside-in": 198.23,
}

area_m2_by_config = {
    config: area_mm2 * 1e-6
    for config, area_mm2 in area_mm2_by_config.items()
}

mps_to_uL_min_cm2 = 6e6

OUTPUT_DIR = "Vmax_sweep_model_derived_clearance_plots"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ============================================================
# 2) FONT SETTINGS
# ============================================================

plt.rcParams.update({
    "font.size": 18,
    "axes.titlesize": 28,
    "axes.labelsize": 24,
    "xtick.labelsize": 20,
    "ytick.labelsize": 20,
    "legend.fontsize": 20,
    "legend.title_fontsize": 22,
})

# ============================================================
# 3) FILE PATHS
# ============================================================

vmax_values = [1e2, 1e3, 1e4, 1e5, 1e6, 1e7, 1e8, 1e9]
reference_vmax = 1e6

config_files = {
    "Inside-out": {
        1e2: "IO_countercurrent_Vmax1e2.txt",
        1e3: "IO_countercurrent_Vmax1e3.txt",
        1e4: "IO_countercurrent_Vmax1e4.txt",
        1e5: "IO_countercurrent_Vmax1e5.txt",
        1e6: "IO_countercurrent_Vmax1e6.txt",
        1e7: "IO_countercurrent_Vmax1e7.txt",
        1e8: "IO_countercurrent_Vmax1e8.txt",
        1e9: "totalnormalflux_IO_countercurrent_Vmax1e9_bm.txt",
    },
    "Outside-in": {
        1e2: "OI_countercurrent_Vmax1e2.txt",
        1e3: "OI_countercurrent_Vmax1e3.txt",
        1e4: "OI_countercurrent_Vmax1e4.txt",
        1e5: "OI_countercurrent_Vmax1e5.txt",
        1e6: "OI_countercurrent_Vmax1e6.txt",
        1e7: "OI_countercurrent_Vmax1e7.txt",
        1e8: "OI_countercurrent_Vmax1e8.txt",
        1e9: "totalnormalflux_OI_countercurrent_Vmax1e9_bm.txt",
    },
    "Adjusted outside-in": {
        1e2: "adjustedOI_countercurrent_Vmax1e2.txt",
        1e3: "adjustedOI_countercurrent_Vmax1e3.txt",
        1e4: "adjusted_OI_countercurrent_Vmax1e4.txt",
        1e5: "adjusted_OI_countercurrent_Vmax1e5.txt",
        1e6: "adjusted_OI_countercurrent_Vmax1e6.txt",
        1e7: "adjusted_OI_countercurrent_Vmax1e7.txt",
        1e8: "adjusted_OI_countercurrent_Vmax1e8.txt",
        1e9: "totalnormalflux_adjustedOI_countercurrent_Vmax1e9_bm.txt",
    },
}

colors = {
    "Inside-out": "tab:blue",
    "Outside-in": "tab:orange",
    "Adjusted outside-in": "tab:green",
}

# ============================================================
# 4) HELPER FUNCTIONS
# ============================================================

def load_flux_file_auto_time(filepath):
    data = np.loadtxt(filepath, comments="%")

    time_raw = data[:, 0]
    flux_mol_s = data[:, 1]

    if time_raw[-1] > 1000:
        time_min = time_raw / 60.0
    else:
        time_min = time_raw

    return time_min, flux_mol_s


def compute_model_derived_clearance(filepath, config_name):
    time_min, flux_mol_s = load_flux_file_auto_time(filepath)

    time_sec = time_min * 60.0
    total_mol = np.trapz(flux_mol_s, time_sec)

    A_m2 = area_m2_by_config[config_name]

    CL_model_m_s = total_mol / (time_sec[-1] * A_m2 * C_in)
    CL_model_uL_min_cm2 = abs(CL_model_m_s * mps_to_uL_min_cm2)

    return CL_model_uL_min_cm2


def percent_difference(value, reference_value):
    return ((value - reference_value) / reference_value) * 100.0


def format_percent_difference(percent_diff):
    if np.isclose(percent_diff, 0.0):
        return "0.00%"
    return f"{percent_diff:+.2f}%"


def save_current_figure(filename):
    plt.tight_layout()

    plt.savefig(
        os.path.join(OUTPUT_DIR, filename),
        dpi=300,
        bbox_inches="tight"
    )

    plt.show()


def add_horizontal_bar_labels(
    bars,
    values,
    reference_value,
    log_scale=False,
    label_x_shift=0.0,
):
    for bar, value in zip(bars, values):

        percent_diff = percent_difference(value, reference_value)

        if log_scale:
            y_pos = value * 1.10
        else:
            y_pos = value + 0.03 * max(values)

        plt.text(
            bar.get_x() + bar.get_width() / 2 + label_x_shift,
            y_pos,
            f"{value:.3f}\n({format_percent_difference(percent_diff)})",
            ha="center",
            va="bottom",
            fontsize=12,
            fontweight="bold",
        )

# ============================================================
# 5) COMPUTE END POINT TIME-AVERAGE CLEARANCE
# ============================================================

clearance_by_config = {}

print("=" * 90)
print("END POINT TIME-AVERAGE CLEARANCE VALUES: Vmax SWEEP")
print("=" * 90)

for config_name, files_for_config in config_files.items():

    clearance_by_config[config_name] = []

    print(
        f"{config_name:22s} | "
        f"Area = {area_mm2_by_config[config_name]:.2f} mm^2"
    )

    for vmax in vmax_values:

        filepath = files_for_config[vmax]

        if not os.path.exists(filepath):
            raise FileNotFoundError(f"Missing file: {filepath}")

        clearance = compute_model_derived_clearance(filepath, config_name)

        clearance_by_config[config_name].append(clearance)

        print(
            f"{config_name:22s} | "
            f"Vmax = {vmax:.0e} | "
            f"End point time-average clearance = "
            f"{clearance:.6f} uL/(min*cm^2)"
        )

print("=" * 90)

# ============================================================
# ============================================================
# 6A) PLOT 1 : Vmax = 1e4 -> 1e9
# ============================================================

vmax_values_plot1 = [1e4, 1e5, 1e6, 1e7, 1e8, 1e9]

fig, ax = plt.subplots(figsize=(18, 10))

group_spacing = 1.6
x = np.arange(len(vmax_values_plot1)) * group_spacing

bar_width = 0.24

all_values = []

for i, config_name in enumerate(config_files.keys()):

    full_values = clearance_by_config[config_name]

    values = [
        full_values[vmax_values.index(v)]
        for v in vmax_values_plot1
    ]

    all_values.extend(values)

    reference_value = full_values[
        vmax_values.index(reference_vmax)
    ]

    offset = (i - 1) * bar_width * 1.6

    bars = ax.bar(
        x + offset,
        values,
        width=bar_width,
        color=colors[config_name],
        label=config_name,
    )

    for bar, value in zip(bars, values):

        percent_diff = percent_difference(
            value,
            reference_value
        )

        y_pos = value + 0.03 * max(all_values)

        ax.text(
            bar.get_x() + bar.get_width()/2,
            y_pos,
            f"{value:.3f}\n({format_percent_difference(percent_diff)})",
            ha="center",
            va="bottom",
            rotation=90,
            fontsize=18,
            fontweight="bold",
        )

ax.set_ylim(0, max(all_values) * 1.75)

ax.set_xticks(x)
ax.set_xticklabels([f"{v:.0e}" for v in vmax_values_plot1])

ax.set_xlabel(
    "Vmax (umol/(L·min))",
    fontweight="bold",
)

ax.set_ylabel(
    "End point time-average clearance\n"
    "(uL/(min·cm$^2$))",
    fontweight="bold",
)

ax.set_title(
    "End point time-average clearance vs Vmax\n",
    fontweight="bold",
)

ax.grid(True, axis="y", alpha=0.3)

ax.legend(
    title="Configuration",
    loc="upper center",
    bbox_to_anchor=(0.5, -0.12),
    ncol=3,
)

save_current_figure(
    "model_derived_clearance_Vmax1e4_to_1e9.png"
)


# ============================================================
# 6B) PLOT 2 : Vmax = 1e2 -> 1e9
# ============================================================

vmax_values_plot2 = [1e2, 1e3, 1e4, 1e5, 1e6, 1e7, 1e8, 1e9]

fig, ax = plt.subplots(figsize=(22, 10))

group_spacing = 1.6
x = np.arange(len(vmax_values_plot2)) * group_spacing

bar_width = 0.24

all_values = []

for i, config_name in enumerate(config_files.keys()):

    values = clearance_by_config[config_name]

    all_values.extend(values)

    reference_value = values[
        vmax_values.index(reference_vmax)
    ]

    offset = (i - 1) * bar_width * 1.6

    bars = ax.bar(
        x + offset,
        values,
        width=bar_width,
        color=colors[config_name],
        label=config_name,
    )

    for bar, value in zip(bars, values):

        percent_diff = percent_difference(
            value,
            reference_value
        )

        y_pos = value + 0.03 * max(all_values)

        ax.text(
            bar.get_x() + bar.get_width()/2,
            y_pos,
            f"{value:.3f}\n({format_percent_difference(percent_diff)})",
            ha="center",
            va="bottom",
            rotation=90,
            fontsize=18,
            fontweight="bold",
        )

ax.set_ylim(0, max(all_values) * 1.75)

ax.set_xticks(x)
ax.set_xticklabels([f"{v:.0e}" for v in vmax_values_plot2])

ax.set_xlabel(
    "Vmax (umol/(L·min))",
    fontweight="bold",
)

ax.set_ylabel(
    "End point time-average clearance\n"
    "(uL/(min·cm$^2$))",
    fontweight="bold",
)

ax.set_title(
    "End point time-average clearance vs Vmax\n",
    fontweight="bold",
)

ax.grid(True, axis="y", alpha=0.3)

ax.legend(
    title="Configuration",
    loc="upper center",
    bbox_to_anchor=(0.5, -0.12),
    ncol=3,
)

save_current_figure(
    "model_derived_clearance_Vmax1e2_to_1e9.png"
)

OUTPUT_DIR = "total_normal_flux_all_configs_plots"
os.makedirs(OUTPUT_DIR, exist_ok=True)

vmax_values = [1e2, 1e3, 1e4, 1e5, 1e6, 1e7, 1e8, 1e9]
reference_vmax = 1e6

# ============================================================
# 2) FONT SETTINGS
# ============================================================

plt.rcParams.update({
    "font.size": 18,
    "axes.titlesize": 28,
    "axes.labelsize": 24,
    "xtick.labelsize": 20,
    "ytick.labelsize": 20,
    "legend.fontsize": 20,
    "legend.title_fontsize": 22,
})

# ============================================================
# 3) FILE PATHS
# ============================================================

config_files = {
    "Inside-out": {
        1e2: "totalnormalflux_IO_countercurrent_cd_Vmax1e2.txt",
        1e3: "totalnormalflux_IO_countercurrent_cd_Vmax1e3.txt",
        1e4: "totalnormalflux_IO_countercurrent_cd_Vmax1e4.txt",
        1e5: "totalnormalflux_IO_countercurrent_cd_Vmax1e5.txt",
        1e6: "totalnormalflux_IO_countercurrent_cd_Vmax1e6.txt",
        1e7: "totalnormalflux_IO_countercurrent_cd_Vmax1e7.txt",
        1e8: "totalnormalflux_IO_countercurrent_cd_Vmax1e8.txt",
        1e9: "totalnormalflux_IO_countercurrent_Vmax1e9_cd.txt",
    },

    "Outside-in": {
        1e2: "totalnormalflux_OI_countercurrent_cd_Vmax1e2.txt",
        1e3: "totalnormalflux_OI_countercurrent_cd_Vmax1e3.txt",
        1e4: "totalnormalflux_OI_countercurrent_cd_Vmax1e4.txt",
        1e5: "totalnormalflux_OI_countercurrent_cd_Vmax1e5.txt",
        1e6: "totalnormalflux_OI_countercurrent_cd_Vmax1e6.txt",
        1e7: "totalnormalflux_OI_countercurrent_cd_Vmax1e7.txt",
        1e8: "totalnormalflux_OI_countercurrent_cd_Vmax1e8.txt",
        1e9: "totalnormalflux_OI_countercurrent_Vmax1e9_cd.txt",
    },

    "Adjusted outside-in": {
        1e2: "totalnormalflux_adjustedOI_countercurrent_cd_Vmax1e2.txt",
        1e3: "totalnormalflux_adjustedOI_countercurrent_cd_Vmax1e3.txt",
        1e4: "totalnormalflux_adjustedOI_countercurrent_cd_Vmax1e4.txt",
        1e5: "totalnormalflux_adjustedOI_countercurrent_cd_Vmax1e5.txt",
        1e6: "totalnormalflux_adjustedOI_countercurrent_cd_Vmax1e6.txt",
        1e7: "totalnormalflux_adjustedOI_countercurrent_cd_Vmax1e7.txt",
        1e8: "totalnormalflux_adjustedOI_countercurrent_cd_Vmax1e8.txt",
        1e9: "totalnormalflux_adjustedOI_countercurrent_Vmax1e9_cd.txt",
    },
}

# ============================================================
# 4) COLORS
# ============================================================

colors = {
    "Inside-out": "tab:blue",
    "Outside-in": "tab:orange",
    "Adjusted outside-in": "tab:green",
}

# ============================================================
# 5) HELPER FUNCTIONS
# ============================================================

def load_flux_file(filepath):

    data = np.loadtxt(filepath, comments="%")

    time_min = data[:, 0]
    total_normal_flux_mol_s = data[:, 1]

    return time_min, total_normal_flux_mol_s


def get_flux_at_240min(filepath, config_name):

    time_min, flux_mol_s = load_flux_file(filepath)

    flux_value = flux_mol_s[-1]

    if config_name in ["Outside-in", "Adjusted outside-in"]:
        flux_value = -flux_value

    return flux_value


def percent_difference(value, reference_value):

    return (
        (value - reference_value)
        / reference_value
    ) * 100.0


def format_percent_difference(percent_diff):

    if np.isclose(percent_diff, 0.0):
        return "0.00%"

    return f"{percent_diff:+.2f}%"


def save_current_figure(filename):

    plt.tight_layout()

    plt.savefig(
        os.path.join(OUTPUT_DIR, filename),
        dpi=300,
        bbox_inches="tight",
    )

    plt.show()


def add_bar_labels(
    bars,
    values,
    reference_value,
    x_shift=0.0,
):

    max_value = max(values)

    for i, (bar, value) in enumerate(zip(bars, values)):

        percent_diff = percent_difference(
            value,
            reference_value
        )

        # Vertical staggering to reduce overlap
        stagger = (i % 2) * 0.025 * max_value

        plt.text(
            bar.get_x() + bar.get_width() / 2 + x_shift,

            value + 0.04 * max_value + stagger,

            f"({format_percent_difference(percent_diff)})",

            ha="center",
            va="bottom",

            fontsize=12,
            fontweight="bold",
            rotation=0,
        )

# ============================================================
# 6) EXTRACT TOTAL NORMAL FLUX AT 240 MIN
# ============================================================

flux_by_config = {}

print("=" * 90)
print("TOTAL NORMAL FLUX VALUES AT 240 MIN")
print("=" * 90)

for config_name, files_for_config in config_files.items():

    flux_by_config[config_name] = []

    for vmax in vmax_values:

        filepath = files_for_config[vmax]

        if not os.path.exists(filepath):

            raise FileNotFoundError(
                f"Missing file: {filepath}"
            )

        flux_value = get_flux_at_240min(
            filepath,
            config_name
        )

        flux_by_config[config_name].append(
            flux_value
        )

        print(
            f"{config_name:22s} | "
            f"Vmax = {vmax:.0e} | "
            f"Total normal flux = {flux_value:.6e} mol/s"
        )

print("=" * 90)

# ============================================================
# ============================================================
# ============================================================
# 7A) PLOT 1 : Vmax = 1e4 -> 1e9
# ============================================================

vmax_values_plot1 = [1e4, 1e5, 1e6, 1e7, 1e8, 1e9]

fig, ax = plt.subplots(figsize=(18, 10))

group_spacing = 1.6
x = np.arange(len(vmax_values_plot1)) * group_spacing
bar_width = 0.24

all_values = []

for i, config_name in enumerate(config_files.keys()):

    full_values = flux_by_config[config_name]

    values = [
        full_values[vmax_values.index(v)]
        for v in vmax_values_plot1
    ]

    all_values.extend(values)

    reference_value = full_values[
        vmax_values.index(reference_vmax)
    ]

    offset = (i - 1) * bar_width * 1.6

    bars = ax.bar(
        x + offset,
        values,
        width=bar_width,
        color=colors[config_name],
        label=config_name,
    )

    for bar, value in zip(bars, values):

        percent_diff = percent_difference(
            value,
            reference_value
        )

        y_pos = value + 0.03 * max(all_values)

        ax.text(
            bar.get_x() + bar.get_width() / 2,
            y_pos,
            f"{format_percent_difference(percent_diff)}",
            ha="center",
            va="bottom",
            rotation=90,
            fontsize=18,
            fontweight="bold",
        )

ax.set_ylim(0, max(all_values) * 1.75)

ax.set_xticks(x)
ax.set_xticklabels([f"{v:.0e}" for v in vmax_values_plot1])

ax.set_xlabel(
    "Vmax (umol/(L·min))",
    fontweight="bold",
)

ax.set_ylabel(
    "Total Normal Flux from Cell to Dialysate\n"
    "(mol/s)",
    fontweight="bold",
)

ax.set_title(
    "Total Normal Flux from Cell to Dialysate vs Vmax\n",
    fontweight="bold",
)

ax.grid(True, axis="y", alpha=0.3)

ax.legend(
    title="Configuration",
    loc="upper center",
    bbox_to_anchor=(0.5, -0.12),
    ncol=3,
)

save_current_figure(
    "total_normal_flux_all_configs_240min_Vmax1e4_to_1e9.png"
)


# ============================================================
# 7B) PLOT 2 : Vmax = 1e2 -> 1e9
# ============================================================

vmax_values_plot2 = [1e2, 1e3, 1e4, 1e5, 1e6, 1e7, 1e8, 1e9]

fig, ax = plt.subplots(figsize=(22, 10))

group_spacing = 1.6
x = np.arange(len(vmax_values_plot2)) * group_spacing
bar_width = 0.24

all_values = []

for i, config_name in enumerate(config_files.keys()):

    values = flux_by_config[config_name]

    all_values.extend(values)

    reference_value = values[
        vmax_values.index(reference_vmax)
    ]

    offset = (i - 1) * bar_width * 1.6

    bars = ax.bar(
        x + offset,
        values,
        width=bar_width,
        color=colors[config_name],
        label=config_name,
    )

    for bar, value in zip(bars, values):

        percent_diff = percent_difference(
            value,
            reference_value
        )

        y_pos = value + 0.03 * max(all_values)

        ax.text(
            bar.get_x() + bar.get_width() / 2,
            y_pos,
            f"{format_percent_difference(percent_diff)}",
            ha="center",
            va="bottom",
            rotation=90,
            fontsize=18,
            fontweight="bold",
        )

ax.set_ylim(0, max(all_values) * 1.75)

ax.set_xticks(x)
ax.set_xticklabels([f"{v:.0e}" for v in vmax_values_plot2])

ax.set_xlabel(
    "Vmax (umol/(L·min))",
    fontweight="bold",
)

ax.set_ylabel(
    "Total Normal Flux from Cell to Dialysate\n"
    "(mol/s)",
    fontweight="bold",
)

ax.set_title(
    "Total Normal Flux from Cell to Dialysate vs Vmax\n",
    fontweight="bold",
)

ax.grid(True, axis="y", alpha=0.3)

ax.legend(
    title="Configuration",
    loc="upper center",
    bbox_to_anchor=(0.5, -0.12),
    ncol=3,
)

save_current_figure(
    "total_normal_flux_all_configs_240min_Vmax1e2_to_1e9.png"
)



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.patches import Patch

# ============================================================
# FILE
# ============================================================

file = "radialconcentrationdistribution_IO_countercurrent_Vmax_parasweep.txt"

# ============================================================
# Vmax + time labels
# Order must match COMSOL export order
# ============================================================

VMAX_TIME_INFO = [
    {"Vmax": "10000 µmol/(L·min)", "time": "0 min"},
    {"Vmax": "10000 µmol/(L·min)", "time": "100 min"},
    {"Vmax": "1E8 µmol/(L·min)",   "time": "0 min"},
    {"Vmax": "1E8 µmol/(L·min)",   "time": "100 min"},
]

# ============================================================
# CURVE COLORS
# Same style as your axial-position legend
# ============================================================

CURVE_COLORS = [
    "#00429d",  # dark blue
    "#2ca02c",  # green
    "#ff7f0e",  # orange
    "#9467bd",  # purple
]

# ============================================================
# DOMAIN DEFINITIONS
# ============================================================

blood_start, blood_end = 0.00, 0.15
mem_start, mem_end     = 0.15, 0.25
cell_start, cell_end   = 0.25, 0.27
dial_start, dial_end   = 0.27, 1.80

DOMAIN_COLORS = {
    "Blood": "#d6f5d6",
    "Membrane": "#f4c2c2",
    "Cell": "#ffd9b3",
    "Dialysate": "#cfe8ff",
}

# ============================================================
# LOAD FILE
# ============================================================

df = pd.read_csv(
    file,
    comment="%",
    sep=r"\s+",
    header=None,
    engine="python"
)

df.columns = ["R", "C"]

# ============================================================
# SPLIT INTO BLOCKS
# Each curve starts again at R = 0
# ============================================================

block_starts = df.index[np.isclose(df["R"], 0.0)].tolist()
block_starts.append(len(df))

datasets = []

for i in range(len(block_starts) - 1):

    start = block_starts[i]
    end   = block_starts[i + 1]

    block = df.iloc[start:end].copy()

    block = block.sort_values("R").reset_index(drop=True)

    info = VMAX_TIME_INFO[i]

    datasets.append({
        "R": block["R"].to_numpy(),
        "C": block["C"].to_numpy(),
        "Vmax": info["Vmax"],
        "time": info["time"],
        "color": CURVE_COLORS[i]
    })

# ============================================================
# FIGURE
# ============================================================

fig, ax = plt.subplots(figsize=(13, 7), dpi=140)

# ============================================================
# DOMAIN SHADING
# ============================================================

ax.axvspan(
    blood_start,
    blood_end,
    color=DOMAIN_COLORS["Blood"],
    alpha=0.25
)

ax.axvspan(
    mem_start,
    mem_end,
    color=DOMAIN_COLORS["Membrane"],
    alpha=0.25
)

ax.axvspan(
    cell_start,
    cell_end,
    color=DOMAIN_COLORS["Cell"],
    alpha=0.25
)

ax.axvspan(
    dial_start,
    dial_end,
    color=DOMAIN_COLORS["Dialysate"],
    alpha=0.25
)

# ============================================================
# PLOT CURVES
# ============================================================

for d in datasets:

    ax.plot(
        d["R"],
        d["C"],
        color=d["color"],
        lw=2.8,
        label=f"Vmax={d['Vmax']}, Time={d['time']}"
    )

# ============================================================
# DOMAIN BOUNDARIES
# ============================================================

for x in [0.15, 0.25, 0.27]:

    ax.axvline(
        x,
        color="gray",
        linestyle="--",
        linewidth=1
    )

# ============================================================
# ============================================================
# LABELS
# ============================================================

ax.set_title(
    "Molar concentration profile for different Vmax values at z = 10 mm",
    fontsize=24,
    fontweight="bold"
)

ax.set_xlabel(
    "Arc length (mm)",
    fontsize=20,
    fontweight="bold"
)

ax.set_ylabel(
    "Molar concentration, IS (mol/m³)",
    fontsize=20,
    fontweight="bold"
)

# Bigger tick labels
ax.tick_params(
    axis="both",
    which="major",
    labelsize=16
)

ax.set_xlim(0, 1.8)

ax.grid(alpha=0.3)

# ============================================================
# LEGEND 1 — Vmax + Time
# ============================================================

curve_handles = [
    Line2D(
        [0], [0],
        color=d["color"],
        lw=3.5,
        label=f"Vmax={d['Vmax']}, Time={d['time']}"
    )
    for d in datasets
]

legend1 = ax.legend(
    handles=curve_handles,
    title="Vmax and times plotted",
    loc="upper right",
    bbox_to_anchor=(0.99, 0.88),
    fontsize=12,
    title_fontsize=14,
    frameon=True,
    borderpad=0.8,
    labelspacing=0.6
)

ax.add_artist(legend1)

# ============================================================
# LEGEND 2 — DOMAINS
# ============================================================

domain_handles = [
    Patch(facecolor=DOMAIN_COLORS["Blood"], edgecolor="black", alpha=0.35,
          label="Blood: 0–0.15 mm"),
    Patch(facecolor=DOMAIN_COLORS["Membrane"], edgecolor="black", alpha=0.35,
          label="Membrane: 0.15–0.25 mm"),
    Patch(facecolor=DOMAIN_COLORS["Cell"], edgecolor="black", alpha=0.35,
          label="Cell: 0.25–0.27 mm"),
    Patch(facecolor=DOMAIN_COLORS["Dialysate"], edgecolor="black", alpha=0.35,
          label="Dialysate: 0.27–1.80 mm"),
    Line2D([0], [0], color="gray", linestyle="--", lw=1.5,
           label="Domain boundaries"),
]

legend2 = ax.legend(
    handles=domain_handles,
    title="Domains",
    loc="lower right",
    bbox_to_anchor=(0.99, 0.02),
    fontsize=12,
    title_fontsize=14,
    frameon=True,
    borderpad=0.8,
    labelspacing=0.6
)

ax.add_artist(legend2)

# ============================================================
# ANNOTATIONS
# ============================================================

# Concentration gradient arrow
ax.annotate(
    "",
    xy=(0.23, 0.055),
    xytext=(0.23, 0.098),
    arrowprops=dict(
        arrowstyle="<->",
        color="#00429d",
        lw=3
    )
)

ax.text(
    0.245,
    0.073,
    "Concentration\ngradient",
    color="#00429d",
    fontsize=15,
    fontweight="bold",
    va="center"
)

# Main interpretation text
ax.annotate(
    "Smaller concentration gradient\n"
    "→ less diffusive flux\n"
    "→ lower clearance",

    xy=(0.235, 0.070),
    xytext=(0.42, 0.091),

    arrowprops=dict(
        arrowstyle="->",
        lw=2
    ),

    fontsize=15,
    fontweight="bold",
    ha="left",
    va="center"
)

# Dialysate uptake annotation
ax.annotate(
    "Higher Vmax gives more IS uptake\n"
    "in the dialysate region",

    xy=(0.45, 0.015),
    xytext=(0.55, 0.045),

    arrowprops=dict(
        arrowstyle="->",
        lw=2
    ),

    fontsize=15,
    fontweight="bold",
    ha="left",
    va="center"
)

# ============================================================
# SHOW FIGURE
# ============================================================

plt.show()





from scipy.integrate import trapezoid

results = []

for d in datasets:
    if d["time"] == "100 min":

        R = d["R"]
        C = d["C"]

        # Interpolate concentration at r = 0 and r = 0.25 mm
        C_r0 = np.interp(0.00, R, C)
        C_r025 = np.interp(0.25, R, C)

        delta_C = C_r0 - C_r025

        # Integrate area under curve from r = 0.27 to r = 1.80 mm
        mask = (R >= 0.27) & (R <= 1.80)

        R_int = R[mask]
        C_int = C[mask]

        # Convert mm → m
        R_m = R_int * 1e-3

        # Integrate using SI units
        area = trapezoid(C_int, R_m)

        results.append({
            "Vmax": d["Vmax"],
            "time": d["time"],
            "C(r=0)": C_r0,
            "C(r=0.25)": C_r025,
            "C(r=0) - C(r=0.25)": delta_C,
            "Area r=0.27 to 1.8": area
        })

results_df = pd.DataFrame(results)

pd.set_option("display.float_format", "{:.10e}".format)

print(results_df)

import os
import numpy as np
import matplotlib.pyplot as plt

# ============================================================
# 1) USER INPUTS / CONSTANTS
# ============================================================

C_in = 0.1

area_mm2_by_config = {
    "Inside-out": 31.42,
    "Outside-in": 21.36,
    "Adjusted outside-in": 198.23,
}

area_m2_by_config = {
    config: area_mm2 * 1e-6
    for config, area_mm2 in area_mm2_by_config.items()
}

mps_to_uL_min_cm2 = 6e6

OUTPUT_DIR = "Cis_sweep_model_derived_clearance_plots"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ============================================================
# 2) FONT SETTINGS
# ============================================================

plt.rcParams.update({
    "font.size": 18,
    "axes.titlesize": 28,
    "axes.labelsize": 24,
    "xtick.labelsize": 20,
    "ytick.labelsize": 20,
    "legend.fontsize": 20,
    "legend.title_fontsize": 22,
})

# ============================================================
# 3) FILE PATHS
# ============================================================

cis_values = [50, 75, 100, 125, 150]
reference_cis = 100

config_files = {
    "Inside-out": {
        50: "IO_countercurrent_Cis50.txt",
        75: "IO_countercurrent_Cis75.txt",
        100: "IO_countercurrent_Cis100.txt",
        125: "IO_countercurrent_Cis125.txt",
        150: "IO_countercurrent_Cis150.txt",
    },
    "Outside-in": {
        50: "OI_countercurrent_Cis50.txt",
        75: "OI_countercurrent_Cis75.txt",
        100: "OI_countercurrent_Cis100.txt",
        125: "OI_countercurrent_Cis125.txt",
        150: "OI_countercurrent_Cis150.txt",
    },
    "Adjusted outside-in": {
        50: "adjusted_OI_countercurrent_Cis50.txt",
        75: "adjusted_OI_countercurrent_Cis75.txt",
        100: "adjusted_OI_countercurrent_Cis100.txt",
        125: "adjusted_OI_countercurrent_Cis125.txt",
        150: "adjusted_OI_countercurrent_Cis150.txt",
    },
}

colors = {
    "Inside-out": "tab:blue",
    "Outside-in": "tab:orange",
    "Adjusted outside-in": "tab:green",
}

# ============================================================
# 4) HELPER FUNCTIONS
# ============================================================

def load_flux_file_auto_time(filepath):
    data = np.loadtxt(filepath, comments="%")

    time_raw = data[:, 0]
    flux_mol_s = data[:, 1]

    if time_raw[-1] > 1000:
        time_min = time_raw / 60.0
    else:
        time_min = time_raw

    return time_min, flux_mol_s


def compute_model_derived_clearance(filepath, config_name):
    time_min, flux_mol_s = load_flux_file_auto_time(filepath)

    time_sec = time_min * 60.0
    total_mol = np.trapz(flux_mol_s, time_sec)

    A_m2 = area_m2_by_config[config_name]

    CL_model_m_s = total_mol / (time_sec[-1] * A_m2 * C_in)
    CL_model_uL_min_cm2 = abs(CL_model_m_s * mps_to_uL_min_cm2)

    return CL_model_uL_min_cm2


def percent_difference(value, reference_value):
    return ((value - reference_value) / reference_value) * 100.0


def format_percent_difference(percent_diff):
    if np.isclose(percent_diff, 0.0):
        return "0.00%"
    return f"{percent_diff:+.2f}%"


def save_current_figure(filename):
    plt.tight_layout()

    plt.savefig(
        os.path.join(OUTPUT_DIR, filename),
        dpi=300,
        bbox_inches="tight"
    )

    plt.show()


def add_horizontal_bar_labels(
    bars,
    values,
    reference_value,
    log_scale=False,
    label_x_shift=0.0,
):
    for bar, value in zip(bars, values):

        percent_diff = percent_difference(
            value,
            reference_value
        )

        if log_scale:
            y_pos = value * 1.10
        else:
            y_pos = value + 0.03 * max(values)

        plt.text(
            bar.get_x() + bar.get_width() / 2 + label_x_shift,
            y_pos,
            f"{format_percent_difference(percent_diff)}",
            ha="center",
            va="bottom",
            rotation=90,      # vertical
            fontsize=18,      # bigger
            fontweight="bold",
        )
# ============================================================
# 5) COMPUTE MODEL-DERIVED CLEARANCE FOR ALL CASES
# ============================================================

clearance_by_config = {}

print("=" * 90)
print("MODEL-DERIVED CLEARANCE VALUES: c_is SWEEP")
print("=" * 90)

for config_name, files_for_config in config_files.items():

    clearance_by_config[config_name] = []

    print(
        f"{config_name:22s} | "
        f"Area = {area_mm2_by_config[config_name]:.2f} mm^2"
    )

    for cis in cis_values:

        filepath = files_for_config[cis]

        if not os.path.exists(filepath):
            raise FileNotFoundError(
                f"Missing file for {config_name}, c_is={cis}: {filepath}"
            )

        clearance = compute_model_derived_clearance(filepath, config_name)

        clearance_by_config[config_name].append(clearance)

        print(
            f"{config_name:22s} | "
            f"c_is = {cis:3d} uM | "
            f"Model-derived clearance = "
            f"{clearance:.6f} uL/(min*cm^2)"
        )

print("=" * 90)

# ============================================================
# ============================================================
# 6) BAR PLOT: GROUPED BY c_is
# ============================================================

plt.figure(figsize=(22, 10))

group_spacing = 1.2
x = np.arange(len(cis_values)) * group_spacing

bar_width = 0.18

all_values = []

for i, config_name in enumerate(config_files.keys()):

    values = clearance_by_config[config_name]
    all_values.extend(values)

    reference_value = values[cis_values.index(reference_cis)]

    offset = (i - 1) * bar_width * 1.5
    label_shift = (i - 1) * bar_width * 0.35

    bars = plt.bar(
        x + offset,
        values,
        width=bar_width,
        color=colors[config_name],
        label=config_name,
    )

    for bar, value in zip(bars, values):

        percent_diff = percent_difference(value, reference_value)

        plt.text(
            bar.get_x() + bar.get_width() / 2 + label_shift,
            value + 0.03 * max(values),
            f"{value:.3f}\n({format_percent_difference(percent_diff)})",
            ha="center",
            va="bottom",
            rotation=90,
            fontsize=18,
            fontweight="bold",
        )

plt.ylim(0, max(all_values) * 1.75)

plt.xticks(x, [str(c) for c in cis_values])

plt.xlabel(
    "c_is [uM]",
    fontweight="bold",
    labelpad=15
)

plt.ylabel(
    "End point time-average clearance\n"
    "(uL/(min·cm$^2$))",
    fontweight="bold",
    labelpad=15
)

plt.title(
    "End point time-average clearance vs c_is\n"
    "Countercurrent, 240 min",
    fontweight="bold",
    pad=25
)

plt.grid(True, axis="y", alpha=0.3)

plt.legend(
    title="Configuration",
    loc="upper center",
    bbox_to_anchor=(0.5, -0.12),
    ncol=3,
    frameon=True
)

save_current_figure(
    "model_derived_clearance_countercurrent_Cis_sweep_grouped.png"
)


# ============================================================
# 7) SEPARATE BAR PLOTS: ONE CONFIGURATION PER FIGURE
# ============================================================

for config_name, values in clearance_by_config.items():

    plt.figure(figsize=(10, 7))

    labels = [str(c) for c in cis_values]

    reference_value = values[cis_values.index(reference_cis)]

    bars = plt.bar(
        labels,
        values,
        color=colors[config_name],
        width=0.55,
    )

    for bar, value in zip(bars, values):

        percent_diff = percent_difference(value, reference_value)

        plt.text(
            bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 0.03 * max(values),
            f"{value:.3f}\n({format_percent_difference(percent_diff)})",
            ha="center",
            va="bottom",
            rotation=90,
            fontsize=18,
            fontweight="bold",
        )

    plt.ylim(0, max(values) * 1.75)

    plt.xlabel(
        "c_is [uM]",
        fontweight="bold",
        labelpad=12
    )

    plt.ylabel(
        "End point time-average clearance\n"
        "(uL/(min·cm$^2$))",
        fontweight="bold",
        labelpad=12
    )

    plt.title(
        f"End point time-average clearance vs c_is\n"
        f"{config_name}, Countercurrent, 240 min\n"
        f"Area = {area_mm2_by_config[config_name]:.2f} mm$^2$",
        fontweight="bold",
        pad=20
    )

    plt.grid(True, axis="y", alpha=0.3)

    safe_name = (
        config_name.lower()
        .replace(" ", "_")
        .replace("-", "_")
    )

    save_current_figure(
        f"model_derived_clearance_{safe_name}_Cis_sweep.png"
    )

import os
import numpy as np
import matplotlib.pyplot as plt

# ============================================================
# 1) USER INPUTS / CONSTANTS
# ============================================================

C_in = 0.1

area_mm2_by_config = {
    "Inside-out": 31.42,
    "Outside-in": 21.36,
    "Adjusted outside-in": 198.23,
}

area_m2_by_config = {
    config: area_mm2 * 1e-6
    for config, area_mm2 in area_mm2_by_config.items()
}

mps_to_uL_min_cm2 = 6e6

OUTPUT_DIR = "Qblood_sweep_model_derived_clearance_plots"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ============================================================
# 2) FONT SETTINGS
# ============================================================

plt.rcParams.update({
    "font.size": 18,
    "axes.titlesize": 28,
    "axes.labelsize": 24,
    "xtick.labelsize": 20,
    "ytick.labelsize": 20,
    "legend.fontsize": 20,
    "legend.title_fontsize": 22,
})

# ============================================================
# 3) FILE PATHS
# ============================================================

Qblood_values = [4, 5, 6, 7, 8]
reference_Qblood = 6

config_files = {
    "Inside-out": {
        4: "IO_countercurrent_Qblood4.txt",
        5: "IO_countercurrent_Qblood5.txt",
        6: "IO_countercurrent_Qblood6.txt",
        7: "IO_countercurrent_Qblood7.txt",
        8: "IO_countercurrent_Qblood8.txt",
    },
    "Outside-in": {
        4: "OI_countercurrent_Qblood4.txt",
        5: "OI_countercurrent_Qblood5.txt",
        6: "OI_countercurrent_Qblood6.txt",
        7: "OI_countercurrent_Qblood7.txt",
        8: "OI_countercurrent_Qblood8.txt",
    },
    "Adjusted outside-in": {
        4: "adjusted_OI_countercurrent_Qblood4.txt",
        5: "adjusted_OI_countercurrent_Qblood5.txt",
        6: "adjusted_OI_countercurrent_Qblood6.txt",
        7: "adjusted_OI_countercurrent_Qblood7.txt",
        8: "adjusted_OI_countercurrent_Qblood8.txt",
    },
}

colors = {
    "Inside-out": "tab:blue",
    "Outside-in": "tab:orange",
    "Adjusted outside-in": "tab:green",
}

# ============================================================
# 4) HELPER FUNCTIONS
# ============================================================

def load_flux_file_auto_time(filepath):

    data = np.loadtxt(filepath, comments="%")

    time_raw = data[:, 0]
    flux_mol_s = data[:, 1]

    if time_raw[-1] > 1000:
        time_min = time_raw / 60.0
    else:
        time_min = time_raw

    return time_min, flux_mol_s


def compute_model_derived_clearance(filepath, config_name):

    time_min, flux_mol_s = load_flux_file_auto_time(filepath)

    time_sec = time_min * 60.0

    total_mol = np.trapz(flux_mol_s, time_sec)

    A_m2 = area_m2_by_config[config_name]

    CL_model_m_s = (
        total_mol /
        (time_sec[-1] * A_m2 * C_in)
    )

    CL_model_uL_min_cm2 = abs(
        CL_model_m_s * mps_to_uL_min_cm2
    )

    return CL_model_uL_min_cm2


def percent_difference(value, reference_value):

    return (
        (value - reference_value)
        / reference_value
    ) * 100.0


def format_percent_difference(percent_diff):

    if np.isclose(percent_diff, 0.0):
        return "0.00%"

    return f"{percent_diff:+.2f}%"


def save_current_figure(filename):

    plt.tight_layout()

    plt.savefig(
        os.path.join(OUTPUT_DIR, filename),
        dpi=300,
        bbox_inches="tight"
    )

    plt.show()


def add_horizontal_bar_labels(
    bars,
    values,
    reference_value,
    label_x_shift=0.0,
):

    for bar, value in zip(bars, values):

        percent_diff = percent_difference(
            value,
            reference_value
        )

        y_pos = value + 0.03 * max(values)

        plt.text(
            bar.get_x()
            + bar.get_width() / 2
            + label_x_shift,

            y_pos,

            f"{value:.3f}\n"
            f"({format_percent_difference(percent_diff)})",

            ha="center",
            va="bottom",

            rotation=90,
            fontsize=18,
            fontweight="bold",
        )
# ============================================================
# 5) COMPUTE END POINT TIME-AVERAGE CLEARANCE
# ============================================================

clearance_by_config = {}

print("=" * 90)
print("END POINT TIME-AVERAGE CLEARANCE VALUES: Qblood SWEEP")
print("=" * 90)

for config_name, files_for_config in config_files.items():

    clearance_by_config[config_name] = []

    print(
        f"{config_name:22s} | "
        f"Area = "
        f"{area_mm2_by_config[config_name]:.2f} mm^2"
    )

    for Qblood in Qblood_values:

        filepath = files_for_config[Qblood]

        if not os.path.exists(filepath):

            raise FileNotFoundError(
                f"Missing file for "
                f"{config_name}, "
                f"Qblood={Qblood} mL/h: "
                f"{filepath}"
            )

        clearance = compute_model_derived_clearance(
            filepath,
            config_name
        )

        clearance_by_config[config_name].append(
            clearance
        )

        print(
            f"{config_name:22s} | "
            f"Qblood = {Qblood:3d} mL/h | "
            f"End point time-average clearance = "
            f"{clearance:.6f} "
            f"uL/(min*cm^2)"
        )

print("=" * 90)

# ============================================================
# 6) GROUPED BAR PLOT
# ============================================================

plt.figure(figsize=(22, 10))

group_spacing = 1.2

x = np.arange(len(Qblood_values)) * group_spacing

bar_width = 0.18

all_values = []

for i, config_name in enumerate(config_files.keys()):

    values = clearance_by_config[config_name]

    all_values.extend(values)

    reference_value = values[
        Qblood_values.index(reference_Qblood)
    ]

    offset = (i - 1) * bar_width * 1.5

    label_shift = (
        (i - 1)
        * bar_width
        * 0.35
    )

    bars = plt.bar(
        x + offset,
        values,
        width=bar_width,
        color=colors[config_name],
        label=config_name,
    )

    add_horizontal_bar_labels(
        bars=bars,
        values=values,
        reference_value=reference_value,
        label_x_shift=label_shift,
    )

plt.ylim(0, max(all_values) * 1.25)

plt.xticks(
    x,
    [str(q) for q in Qblood_values]
)

plt.xlabel(
    "Qblood [mL/h]",
    fontweight="bold",
    labelpad=15
)

plt.ylabel(
    "End point time-average clearance\n"
    "(uL/(min·cm$^2$))",
    fontweight="bold",
    labelpad=15
)

plt.title(
    "End point time-average clearance vs Qblood\n"
    "Countercurrent, 240 min",
    fontweight="bold",
    pad=25
)

plt.grid(
    True,
    axis="y",
    alpha=0.3
)

plt.legend(
    title="Configuration",
    loc="upper center",
    bbox_to_anchor=(0.5, -0.12),
    ncol=3,
    frameon=True
)

save_current_figure(
    "model_derived_clearance_Qblood_grouped.png"
)

# ============================================================
# 7) SEPARATE BAR PLOTS
# ============================================================

for config_name, values in clearance_by_config.items():

    plt.figure(figsize=(10, 7))

    labels = [str(q) for q in Qblood_values]

    reference_value = values[
        Qblood_values.index(reference_Qblood)
    ]

    bars = plt.bar(
        labels,
        values,
        color=colors[config_name],
        width=0.55,
    )

    for bar, value in zip(bars, values):

        percent_diff = percent_difference(
            value,
            reference_value
        )

        plt.text(
            bar.get_x() + bar.get_width() / 2,

            bar.get_height()
            + 0.02 * max(values),

            f"{value:.3f}\n"
            f"({format_percent_difference(percent_diff)})",

            ha="center",
            va="bottom",

            fontsize=12,
            fontweight="bold",
        )

    plt.ylim(0, max(values) * 1.25)

    plt.xlabel(
        "Qblood [mL/h]",
        fontweight="bold",
        labelpad=12
    )

    plt.ylabel(
        "End point time-average clearance\n"
        "(uL/(min·cm$^2$))",
        fontweight="bold",
        labelpad=12
    )

    plt.title(
        f"End point time-average clearance "
        f"vs Qblood\n"

        f"{config_name}, "
        f"Countercurrent, 240 min\n"

        f"Area = "
        f"{area_mm2_by_config[config_name]:.2f} "
        f"mm$^2$",

        fontweight="bold",
        pad=20
    )

    plt.grid(
        True,
        axis="y",
        alpha=0.3
    )

    safe_name = (
        config_name.lower()
        .replace(" ", "_")
        .replace("-", "_")
    )

    save_current_figure(
        f"model_derived_clearance_"
        f"{safe_name}_Qblood.png"
    )

import os
import numpy as np
import matplotlib.pyplot as plt

# ============================================================
# 1) USER INPUTS / CONSTANTS
# ============================================================

C_in = 0.1

area_mm2_by_config = {
    "Inside-out": 31.42,
    "Outside-in": 21.36,
    "Adjusted outside-in": 198.23,
}

area_m2_by_config = {
    config: area_mm2 * 1e-6
    for config, area_mm2 in area_mm2_by_config.items()
}

mps_to_uL_min_cm2 = 6e6

OUTPUT_DIR = "Qdial_sweep_model_derived_clearance_plots"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ============================================================
# 2) FONT SETTINGS
# ============================================================

plt.rcParams.update({
    "font.size": 18,
    "axes.titlesize": 28,
    "axes.labelsize": 24,
    "xtick.labelsize": 20,
    "ytick.labelsize": 20,
    "legend.fontsize": 20,
    "legend.title_fontsize": 22,
})

# ============================================================
# 3) FILE PATHS
# ============================================================

Qdial_values = [0, 3, 6, 9, 12, 15]
reference_Qdial = 9

config_files = {
    "Inside-out": {
        0: "IO_countercurrent_Qdial0.txt",
        3: "IO_countercurrent_Qdial3.txt",
        6: "IO_countercurrent_Qdial6.txt",
        9: "IO_countercurrent_Qdial9.txt",
        12: "IO_countercurrent_Qdial12.txt",
        15: "IO_countercurrent_Qdial15.txt",
    },
    "Outside-in": {
        0: "OI_countercurrent_Qdial0.txt",
        3: "OI_countercurrent_Qdial3.txt",
        6: "OI_countercurrent_Qdial6.txt",
        9: "OI_countercurrent_Qdial9.txt",
        12: "OI_countercurrent_Qdial12.txt",
        15: "OI_countercurrent_Qdial15.txt",
    },
    "Adjusted outside-in": {
        0: "adjustedOI_countercurrent_Qdial0.txt",
        3: "adjustedOI_countercurrent_Qdial3.txt",
        6: "adjusted_OI_countercurrent_Qdial6.txt",
        9: "adjusted_OI_countercurrent_Qdial9.txt",
        12: "adjusted_OI_countercurrent_Qdial12.txt",
        15: "adjusted_OI_countercurrent_Qdial15.txt",
    },
}

colors = {
    "Inside-out": "tab:blue",
    "Outside-in": "tab:orange",
    "Adjusted outside-in": "tab:green",
}

# ============================================================
# 4) HELPER FUNCTIONS
# ============================================================

def load_flux_file_auto_time(filepath):
    data = np.loadtxt(filepath, comments="%")

    time_raw = data[:, 0]
    flux_mol_s = data[:, 1]

    if time_raw[-1] > 1000:
        time_min = time_raw / 60.0
    else:
        time_min = time_raw

    return time_min, flux_mol_s


def compute_model_derived_clearance(filepath, config_name):
    time_min, flux_mol_s = load_flux_file_auto_time(filepath)

    time_sec = time_min * 60.0
    total_mol = np.trapz(flux_mol_s, time_sec)

    A_m2 = area_m2_by_config[config_name]

    CL_model_m_s = total_mol / (time_sec[-1] * A_m2 * C_in)
    CL_model_uL_min_cm2 = abs(CL_model_m_s * mps_to_uL_min_cm2)

    return CL_model_uL_min_cm2


def percent_difference(value, reference_value):
    return ((value - reference_value) / reference_value) * 100.0


def format_percent_difference(percent_diff):
    if np.isclose(percent_diff, 0.0):
        return "0.00%"
    return f"{percent_diff:+.2f}%"


def save_current_figure(filename):
    plt.tight_layout()

    plt.savefig(
        os.path.join(OUTPUT_DIR, filename),
        dpi=300,
        bbox_inches="tight"
    )

    plt.show()


def add_horizontal_bar_labels(
    bars,
    values,
    reference_value,
    label_x_shift=0.0,
):

    for bar, value in zip(bars, values):

        percent_diff = percent_difference(
            value,
            reference_value
        )

        y_pos = value + 0.03 * max(values)

        plt.text(
            bar.get_x()
            + bar.get_width() / 2
            + label_x_shift,

            y_pos,

            f"{value:.3f}\n"
            f"({format_percent_difference(percent_diff)})",

            ha="center",
            va="bottom",

            rotation=90,
            fontsize=18,
            fontweight="bold",
        )
# ============================================================
# 5) COMPUTE END POINT TIME-AVERAGE CLEARANCE
# ============================================================

clearance_by_config = {}

print("=" * 90)
print("END POINT TIME-AVERAGE CLEARANCE VALUES: Qdialysate SWEEP")
print("=" * 90)

for config_name, files_for_config in config_files.items():

    clearance_by_config[config_name] = []

    print(
        f"{config_name:22s} | "
        f"Area = {area_mm2_by_config[config_name]:.2f} mm^2"
    )

    for Qdial in Qdial_values:

        filepath = files_for_config[Qdial]

        if not os.path.exists(filepath):
            raise FileNotFoundError(
                f"Missing file for {config_name}, Qdialysate={Qdial} mL/h: {filepath}"
            )

        clearance = compute_model_derived_clearance(filepath, config_name)

        clearance_by_config[config_name].append(clearance)

        print(
            f"{config_name:22s} | "
            f"Qdialysate = {Qdial:3d} mL/h | "
            f"End point time-average clearance = "
            f"{clearance:.6f} uL/(min*cm^2)"
        )

print("=" * 90)

# ============================================================
# 6) GROUPED BAR PLOT
# ============================================================

plt.figure(figsize=(22, 10))

group_spacing = 1.7
x = np.arange(len(Qdial_values)) * group_spacing

bar_width = 0.16

all_values = []

for i, config_name in enumerate(config_files.keys()):

    values = clearance_by_config[config_name]
    all_values.extend(values)

    reference_value = values[Qdial_values.index(reference_Qdial)]

    offset = (i - 1) * bar_width * 1.8
    label_shift = (i - 1) * bar_width * 0.75

    bars = plt.bar(
        x + offset,
        values,
        width=bar_width,
        color=colors[config_name],
        label=config_name,
    )

    add_horizontal_bar_labels(
        bars=bars,
        values=values,
        reference_value=reference_value,
        label_x_shift=label_shift,
    )

plt.ylim(0, max(all_values) * 1.30)

plt.xticks(x, [str(q) for q in Qdial_values])

plt.xlabel(
    "Qdialysate [mL/h]",
    fontweight="bold",
    labelpad=15
)

plt.ylabel(
    "End point time-average clearance\n"
    "(uL/(min·cm$^2$))",
    fontweight="bold",
    labelpad=15
)

plt.title(
    "End point time-average clearance vs Qdialysate\n"
    "Countercurrent, 240 min",
    fontweight="bold",
    pad=25
)

plt.grid(True, axis="y", alpha=0.3)

plt.legend(
    title="Configuration",
    loc="upper center",
    bbox_to_anchor=(0.5, -0.12),
    ncol=3,
    frameon=True
)

save_current_figure(
    "model_derived_clearance_Qdial_grouped.png"
)

# ============================================================
# 7) SEPARATE BAR PLOTS
# ============================================================

for config_name, values in clearance_by_config.items():

    plt.figure(figsize=(10, 7))

    labels = [str(q) for q in Qdial_values]

    reference_value = values[Qdial_values.index(reference_Qdial)]

    bars = plt.bar(
        labels,
        values,
        color=colors[config_name],
        width=0.50,
    )

    for bar, value in zip(bars, values):

        percent_diff = percent_difference(value, reference_value)

        plt.text(
            bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 0.02 * max(values),
            f"{value:.3f}\n({format_percent_difference(percent_diff)})",
            ha="center",
            va="bottom",
            fontsize=12,
            fontweight="bold",
        )

    plt.ylim(0, max(values) * 1.30)

    plt.xlabel(
        "Qdialysate [mL/h]",
        fontweight="bold",
        labelpad=12
    )

    plt.ylabel(
        "End point time-average clearance\n"
        "(uL/(min·cm$^2$))",
        fontweight="bold",
        labelpad=12
    )

    plt.title(
        f"End point time-average clearance vs Qdialysate\n"
        f"{config_name}, Countercurrent, 240 min\n"
        f"Area = {area_mm2_by_config[config_name]:.2f} mm$^2$",
        fontweight="bold",
        pad=20
    )

    plt.grid(True, axis="y", alpha=0.3)

    safe_name = (
        config_name.lower()
        .replace(" ", "_")
        .replace("-", "_")
    )

    save_current_figure(
        f"model_derived_clearance_{safe_name}_Qdial.png"
    )

