# -*- coding: utf-8 -*-
"""radial_profiles_countercurrent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oIayLqZSlthjwkXqBtzk4FmWuuWDbYlz
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.patches import Patch

# ============================================================
# FILES
# ============================================================

files = {
    "z = 0.5 mm":  "radialconcentrationprofile_IO_countercurrent_0.5mm.txt",
    "z = 5 mm":    "radialconcentrationprofile_IO_countercurrent_5mm.txt",
    "z = 10 mm":   "radialconcentrationprofile_IO_countercurrent_10mm.txt",
    "z = 15 mm":   "radialconcentrationprofile_IO_countercurrent_15mm.txt",
    "z = 19.5 mm": "radialconcentrationprofile_IO_countercurrent_19.5mm.txt",
}

# ============================================================
# DOMAIN DEFINITIONS
# ============================================================

blood_start, blood_end = 0.00, 0.15
mem_start, mem_end     = 0.15, 0.25
cell_start, cell_end   = 0.25, 0.27
dial_start, dial_end   = 0.27, 1.80

DOMAIN_COLORS = {
    "Dialysate": "#cfe8ff",
    "Cell": "#ffd9b3",
    "Membrane": "#f4c2c2",
    "Blood": "#d6f5d6",
}

Z_COLORS = {
    "z = 0.5 mm":  "#00429d",
    "z = 5 mm":    "#2ca02c",
    "z = 10 mm":   "#ff7f0e",
    "z = 15 mm":   "#9467bd",
    "z = 19.5 mm": "#000000",
}

r_target = 0.27
zoom_xmin = 0.248
zoom_xmax = 0.285

# ============================================================
# HELPER FUNCTION
# ============================================================

def concentration_at_r(R, C, r0):

    R_np = np.asarray(R, dtype=float)
    C_np = np.asarray(C, dtype=float)

    idx = np.argsort(R_np)

    R_np = R_np[idx]
    C_np = C_np[idx]

    exact = np.where(np.isclose(R_np, r0, atol=1e-12))[0]

    if len(exact) > 0:
        return C_np[exact[0]]

    return np.interp(r0, R_np, C_np)


# ============================================================
# LOAD ALL DATA
# ============================================================

datasets = {}

for z_label, file in files.items():

    df = pd.read_csv(
        file,
        comment="%",
        sep=r"\s+",
        header=None,
        engine="python"
    )

    df = df.sort_values(by=0).reset_index(drop=True)

    R = df[0].to_numpy()

    # 0 min
    c_t0 = df[2].to_numpy()

    # 5 minutes
    c_t5 = df[3].to_numpy()

    datasets[z_label] = {
        "R": R,
        "c_t0": c_t0,
        "c_t5": c_t5,
        "c0_at_target": concentration_at_r(R, c_t0, r_target),
        "c5_at_target": concentration_at_r(R, c_t5, r_target),
    }


# ============================================================
# LEGEND HANDLES
# ============================================================

z_handles = [
    Line2D([0], [0], color=Z_COLORS[k], lw=4, label=k)
    for k in Z_COLORS
]

time_handles = [
    Line2D([0], [0], color="black", lw=4, linestyle="--", label="0 min"),
    Line2D([0], [0], color="black", lw=4, linestyle="-",  label="t = 5 minutes"),
]

domain_handles = [
    Patch(color=DOMAIN_COLORS["Blood"], label="Blood: 0–0.15 mm", alpha=0.4),
    Patch(color=DOMAIN_COLORS["Membrane"], label="Membrane: 0.15–0.25 mm", alpha=0.4),
    Patch(color=DOMAIN_COLORS["Cell"], label="Cell: 0.25–0.27 mm", alpha=0.4),
    Patch(color=DOMAIN_COLORS["Dialysate"], label="Dialysate: 0.27–1.80 mm", alpha=0.4),
    Line2D([0], [0], color="gray", linestyle="--", linewidth=2, label="Domain boundaries"),
]


# ============================================================
# FIGURE 1 — FULL PROFILE
# ============================================================

fig1, ax1 = plt.subplots(figsize=(13, 7), dpi=140)

ax1.axvspan(blood_start, blood_end, color=DOMAIN_COLORS["Blood"], alpha=0.25)
ax1.axvspan(mem_start, mem_end, color=DOMAIN_COLORS["Membrane"], alpha=0.25)
ax1.axvspan(cell_start, cell_end, color=DOMAIN_COLORS["Cell"], alpha=0.25)
ax1.axvspan(dial_start, dial_end, color=DOMAIN_COLORS["Dialysate"], alpha=0.25)

for z_label, data in datasets.items():

    color = Z_COLORS[z_label]

    ax1.plot(data["R"], data["c_t0"], lw=3.5, color=color, linestyle="--")
    ax1.plot(data["R"], data["c_t5"], lw=3.5, color=color, linestyle="-")

for x in [0.15, 0.25, 0.27]:
    ax1.axvline(x, color="gray", linestyle="--", linewidth=1.5)

ax1.set_title(
    "Molar concentration profile at different axial positions",
    fontsize=22,
    fontweight="bold"
)

ax1.set_xlabel(
    "Arc length (mm)",
    fontsize=20,
    fontweight="bold"
)

ax1.set_ylabel(
    "Molar concentration (mol/m³)",
    fontsize=20,
    fontweight="bold"
)

ax1.tick_params(axis="both", labelsize=17)

ax1.set_xlim(0, 1.8)
ax1.grid(alpha=0.3)

legend1 = ax1.legend(
    handles=z_handles,
    title="Axial position",
    loc="upper right",
    fontsize=18,
    title_fontsize=20,
    framealpha=0.95
)

ax1.add_artist(legend1)

legend2 = ax1.legend(
    handles=time_handles + domain_handles,
    title="Time / domains",
    loc="center",
    bbox_to_anchor=(0.58, 0.35),
    fontsize=18,
    title_fontsize=20,
    framealpha=0.95
)

ax1.add_artist(legend2)

plt.tight_layout()
plt.show()


# ============================================================
# FIGURE 2 — ZOOM NEAR r = 0.27 mm
# ============================================================

fig2, ax2 = plt.subplots(figsize=(13, 7), dpi=140)

ax2.axvspan(mem_start, mem_end, color=DOMAIN_COLORS["Membrane"], alpha=0.25)
ax2.axvspan(cell_start, cell_end, color=DOMAIN_COLORS["Cell"], alpha=0.25)
ax2.axvspan(dial_start, dial_end, color=DOMAIN_COLORS["Dialysate"], alpha=0.25)

zoom_y = []

for z_label, data in datasets.items():

    color = Z_COLORS[z_label]

    R = data["R"]
    c_t0 = data["c_t0"]
    c_t5 = data["c_t5"]

    ax2.plot(R, c_t0, lw=3.5, color=color, linestyle="--")
    ax2.plot(R, c_t5, lw=3.5, color=color, linestyle="-")

    ax2.plot(r_target, data["c0_at_target"], marker="o", ms=7, color=color)
    ax2.plot(r_target, data["c5_at_target"], marker="s", ms=7, color=color)

    mask = (R >= zoom_xmin) & (R <= zoom_xmax)

    zoom_y.extend(c_t0[mask])
    zoom_y.extend(c_t5[mask])

for x in [0.25, 0.27]:
    ax2.axvline(x, color="gray", linestyle="--", linewidth=1.5)

ax2.set_xlim(zoom_xmin, zoom_xmax)

ymin = min(zoom_y)
ymax = max(zoom_y)
ypad = 0.08 * (ymax - ymin)

ax2.set_ylim(ymin - ypad, ymax + ypad)

ax2.set_title(
    "Zoom near r = 0.27 mm",
    fontsize=22,
    fontweight="bold"
)

ax2.set_xlabel(
    "Arc length (mm)",
    fontsize=20,
    fontweight="bold"
)

ax2.set_ylabel(
    "Molar concentration (mol/m³)",
    fontsize=20,
    fontweight="bold"
)

ax2.tick_params(axis="both", labelsize=17)
ax2.grid(alpha=0.3)

# BIG LEGEND 1: axial position
legend_zoom_1 = ax2.legend(
    handles=z_handles,
    title="Axial position",
    loc="upper right",
    fontsize=18,
    title_fontsize=20,
    framealpha=0.95
)

ax2.add_artist(legend_zoom_1)

# BIG LEGEND 2: line meaning
zoom_time_handles = [
    Line2D([0], [0], color="black", lw=4, linestyle="--", label="0 min"),
    Line2D([0], [0], color="black", lw=4, linestyle="-", label="t = 5 minutes"),
]

legend_zoom_2 = ax2.legend(
    handles=zoom_time_handles,
    title="Line / marker meaning",
    loc="lower right",
    fontsize=18,
    title_fontsize=20,
    framealpha=0.95
)

ax2.add_artist(legend_zoom_2)

plt.tight_layout()
plt.show()


# ============================================================
# PRINT VALUES
# ============================================================

print(f"\nConcentration values at r = {r_target:.2f} mm")
print("-" * 68)
print(f"{'Axial position':<14} {'0 min':>16} {'5 minutes':>22}")
print("-" * 68)

for z_label, data in datasets.items():

    print(
        f"{z_label:<14}"
        f"{data['c0_at_target']:>16.6f}"
        f"{data['c5_at_target']:>22.6f}"
    )


# ============================================================
# CONCENTRATION DIFFERENCE AT 1 MINUTE
# Difference = C(r = 0 mm) - C(r = 0.25 mm)
# Only for z = 0.5 mm and z = 19.5 mm
# ============================================================

print("\nConcentration difference at 1 minute")
print("Difference = C(r = 0 mm) - C(r = 0.25 mm)")
print("-" * 80)

for z_label in ["z = 0.5 mm", "z = 19.5 mm"]:

    data = datasets[z_label]

    R = data["R"]

    # This uses df[3].
    # In this plotting script, df[3] is labeled as 5 minutes.
    # If df[3] is actually 1 minute in your COMSOL file, then this is correct.
    c_t1 = data["c_t5"]

    c_r0 = concentration_at_r(R, c_t1, 0.00)
    c_r025 = concentration_at_r(R, c_t1, 0.25)

    difference = c_r0 - c_r025

    print(
        f"{z_label:<12} | "
        f"C(0 mm) = {c_r0:.6e} | "
        f"C(0.25 mm) = {c_r025:.6e} | "
        f"Difference = {difference:.6e}"
    )

import re
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.patches import Patch

# ============================================================
# FOLDER WITH YOUR FILES
# ============================================================

DATA_FOLDER = Path(".")

# ============================================================
# DOMAIN DEFINITIONS
# ============================================================

DOMAINS = {
    "Dialysate": (0.00, 0.15),
    "Cell layer": (0.15, 0.17),
    "Membrane": (0.17, 0.27),
    "Blood lumen": (0.27, 1.80),
}

# ============================================================
# DISTINCT COLORS
# ============================================================

TIME_COLORS = {
    0.0:  "#00429d",
    0.5:  "#2ca02c",
    1.0:  "#d62728",
    2.5:  "#ff7f0e",
    5.0:  "#9467bd",
    10.0: "#000000",
}

TIMES = [0, 0.5, 1, 2.5, 5, 10]

# ============================================================
# DATA READER
# ============================================================

def read_comsol_txt(filepath):

    header_line = None
    data_lines = []

    with open(filepath) as f:
        for line in f:

            if line.startswith("%"):
                candidate = line.strip("%").strip()

                if candidate.startswith("r") and "@ t=" in candidate:
                    header_line = candidate
                continue

            data_lines.append(line.strip())

    columns = re.split(r"\s{2,}", header_line)

    rows = []
    for line in data_lines:
        parts = re.split(r"\s+", line)
        if len(parts) == len(columns):
            rows.append(parts)

    df = pd.DataFrame(rows, columns=columns).astype(float)

    time_map = {}

    for col in df.columns:
        match = re.search(r"@ t=([0-9.]+)", col)
        if match:
            t = float(match.group(1))
            time_map[t] = col

    df = df.sort_values("r")

    return df, time_map


# ============================================================
# DOMAIN SHADING
# ============================================================

def add_domains(ax):

    colors = {
        "Dialysate": "#cfe8ff",
        "Cell layer": "#ffd9b3",
        "Membrane": "#f4c2c2",
        "Blood lumen": "#d6f5d6",
    }

    for name, (x0, x1) in DOMAINS.items():
        ax.axvspan(x0, x1, color=colors[name], alpha=0.25)

    for x in [0.15, 0.17, 0.27]:
        ax.axvline(x, linestyle="--", color="gray", linewidth=1)


def domain_legend():

    return [
        Patch(color="#cfe8ff", label="Dialysate: 0–0.15 mm", alpha=0.4),
        Patch(color="#ffd9b3", label="Cell layer: 0.15–0.17 mm", alpha=0.4),
        Patch(color="#f4c2c2", label="Membrane: 0.17–0.27 mm", alpha=0.4),
        Patch(color="#d6f5d6", label="Blood lumen: 0.27–1.8 mm", alpha=0.4),
        Line2D([0], [0], color="gray", linestyle="--", label="Domain boundaries")
    ]


# ============================================================
# PLOT FUNCTION
# ============================================================

def plot_file(filepath):

    df, time_map = read_comsol_txt(filepath)

    z = re.search(r'z=([0-9.]+)', filepath.name).group(1)

    fig, ax = plt.subplots(figsize=(11, 5), dpi=140)

    for t in TIMES:
        if t in time_map:
            ax.plot(
                df["r"],
                df[time_map[t]],
                color=TIME_COLORS[float(t)],
                linewidth=3,
                label=f"{t} min"
            )

    add_domains(ax)

    ax.set_title(f"Molar concentration profile (z = {z} mm)", fontsize=20)

    ax.set_xlabel("Arc length (mm)", fontsize=18)
    ax.set_ylabel("Molar concentration (mol/m³)", fontsize=18)

    ax.tick_params(axis="both", labelsize=15)

    ax.set_xlim(0, 1.8)

    ax.grid(alpha=0.3)

    leg1 = ax.legend(
        title="Time",
        loc="upper right",
        fontsize=13,
        title_fontsize=15
    )
    ax.add_artist(leg1)

    ax.legend(
    handles=domain_legend(),
    title="Domains / ranges",

    # move legend more toward center
    loc="center",
    bbox_to_anchor=(0.58, 0.35),

    # make legend text larger
    fontsize=20,
    title_fontsize=24,

    framealpha=0.95
)

    plt.tight_layout()

    save_name = f"concentration_profile_z{z}.png"
    plt.savefig(save_name, dpi=300)

    plt.show()


# ============================================================
# PRINT BLOOD TO MEMBRANE DIFFERENCE
# Difference = concentration at r = 1.8 mm - concentration at r = 0.17 mm
# ============================================================

def print_blood_to_membrane_difference(filepath):

    df, time_map = read_comsol_txt(filepath)

    z = re.search(r'z=([0-9.]+)', filepath.name).group(1)

    print("\n" + "=" * 70)
    print(f"Blood-to-membrane concentration difference for z = {z} mm")
    print("Difference = C(r = 1.8 mm) - C(r = 0.17 mm)")
    print("=" * 70)

    for t in TIMES:
        if t in time_map:
            col = time_map[t]

            c_blood = df.loc[(df["r"] - 1.8).abs().idxmin(), col]
            c_membrane = df.loc[(df["r"] - 0.17).abs().idxmin(), col]

            difference = c_blood - c_membrane

            print(
                f"t = {t:>4} min | "
                f"C(1.8 mm) = {c_blood:.6e} | "
                f"C(0.17 mm) = {c_membrane:.6e} | "
                f"Difference = {difference:.6e}"
            )


# ============================================================
# RUN FOR ALL FILES
# ============================================================

files = sorted(DATA_FOLDER.glob(
    "radialconcentrationdistribution_baselineoutsideincountercurrentflow_z=*.txt"
))

for file in files:

    print("Plotting", file.name)
    plot_file(file)

    if file.name.endswith("z=0.5mm.txt") or file.name.endswith("z=19.5mm.txt"):
        print_blood_to_membrane_difference(file)

plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.patches import Patch

# ============================================================
# FILES
# ============================================================

files = {
    "z = 0.5 mm":  "radialconcentrationprofile_adjustedOI_countercurrent_0.5mm.txt",
    "z = 5 mm":    "radialconcentrationprofile_adjustedOI_countercurrent_5mm.txt",
    "z = 10 mm":   "radialconcentrationprofile_adjustedOI_countercurrent_10mm.txt",
    "z = 15 mm":   "radialconcentrationprofile_adjustedOI_countercurrent_15mm.txt",
    "z = 19.5 mm": "radialconcentrationprofile_adjustedOI_countercurrent_19.5mm.txt",
}

# ============================================================
# DOMAIN DEFINITIONS
# ============================================================

dial_start, dial_end   = 0.0000, 1.5575
cell_start, cell_end   = 1.5575, 1.5775
mem_start, mem_end     = 1.5775, 1.6775
blood_start, blood_end = 1.6775, 1.8000

DOMAIN_COLORS = {
    "Dialysate": "#cfe8ff",
    "Cell layer": "#ffd9b3",
    "Membrane": "#f4c2c2",
    "Blood lumen": "#d6f5d6",
}

# ============================================================
# COLORS
# ============================================================

Z_COLORS = {
    "z = 0.5 mm":  "#00429d",
    "z = 5 mm":    "#2ca02c",
    "z = 10 mm":   "#ff7f0e",
    "z = 15 mm":   "#9467bd",
    "z = 19.5 mm": "#000000",
}

# ============================================================
# SETTINGS
# ============================================================

r_target = 1.5575
zoom_xmin = 1.52
zoom_xmax = 1.60

# ============================================================
# HELPER FUNCTION
# ============================================================

def concentration_at_r(R, C, r0):

    R = np.asarray(R, dtype=float)
    C = np.asarray(C, dtype=float)

    idx = np.argsort(R)

    R = R[idx]
    C = C[idx]

    exact = np.where(np.isclose(R, r0, atol=1e-12))[0]

    if len(exact) > 0:
        return C[exact[0]]

    return np.interp(r0, R, C)

# ============================================================
# LOAD DATA
# ============================================================

datasets = {}

for z_label, file in files.items():

    df = pd.read_csv(
        file,
        comment="%",
        sep=r"\s+",
        header=None,
        engine="python"
    )

    df = df.sort_values(by=0).reset_index(drop=True)

    R = df[0].to_numpy()

    # 0 min
    c0 = df[2].to_numpy()

    # 5 minutes
    c5 = df[3].to_numpy()

    datasets[z_label] = {
        "R": R,
        "c0": c0,
        "c5": c5,
        "c0_val": concentration_at_r(R, c0, r_target),
        "c5_val": concentration_at_r(R, c5, r_target),
    }

# ============================================================
# LEGEND HANDLES
# ============================================================

z_handles = [
    Line2D([0], [0], color=Z_COLORS[k], lw=4, label=k)
    for k in Z_COLORS
]

time_handles = [
    Line2D([0], [0], color="black", lw=4, linestyle="--", label="0 min"),
    Line2D([0], [0], color="black", lw=4, linestyle="-",  label="t = 5 minutes"),
]

domain_handles = [
    Patch(color=DOMAIN_COLORS["Dialysate"], label="Dialysate: 0–1.5575 mm", alpha=0.4),
    Patch(color=DOMAIN_COLORS["Cell layer"], label="Cell layer: 1.5575–1.5775 mm", alpha=0.4),
    Patch(color=DOMAIN_COLORS["Membrane"], label="Membrane: 1.5775–1.6775 mm", alpha=0.4),
    Patch(color=DOMAIN_COLORS["Blood lumen"], label="Blood lumen: 1.6775–1.8000 mm", alpha=0.4),
    Line2D([0], [0], color="gray", linestyle="--", linewidth=2, label="Domain boundaries"),
]

# ============================================================
# FIGURE 1 — FULL PROFILE
# ============================================================

fig1, ax1 = plt.subplots(figsize=(13, 7), dpi=140)

# Domain shading
ax1.axvspan(dial_start, dial_end, color=DOMAIN_COLORS["Dialysate"], alpha=0.25)
ax1.axvspan(cell_start, cell_end, color=DOMAIN_COLORS["Cell layer"], alpha=0.25)
ax1.axvspan(mem_start, mem_end, color=DOMAIN_COLORS["Membrane"], alpha=0.25)
ax1.axvspan(blood_start, blood_end, color=DOMAIN_COLORS["Blood lumen"], alpha=0.25)

# Curves
for z_label, data in datasets.items():

    color = Z_COLORS[z_label]

    ax1.plot(
        data["R"],
        data["c0"],
        linestyle="--",
        lw=3.5,
        color=color
    )

    ax1.plot(
        data["R"],
        data["c5"],
        linestyle="-",
        lw=3.5,
        color=color
    )

# Boundaries
for x in [1.5575, 1.5775, 1.6775]:
    ax1.axvline(x, color="gray", linestyle="--", lw=1.5)

# ============================================================
# LABELS
# ============================================================

ax1.set_xlim(0, 1.8)

ax1.set_title(
    "Molar concentration profile at different axial positions",
    fontsize=22,
    fontweight="bold"
)

ax1.set_xlabel(
    "Arc length (mm)",
    fontsize=20,
    fontweight="bold"
)

ax1.set_ylabel(
    "Molar concentration (mol/m³)",
    fontsize=20,
    fontweight="bold"
)

ax1.tick_params(axis="both", labelsize=17)

ax1.grid(alpha=0.3)

# ============================================================
# LEGENDS
# ============================================================

legend_z = ax1.legend(
    handles=z_handles,
    title="Axial position",

    loc="upper left",
    bbox_to_anchor=(0.02, 0.98),

    fontsize=18,
    title_fontsize=20,

    framealpha=0.95
)

ax1.add_artist(legend_z)

legend_time = ax1.legend(
    handles=time_handles + domain_handles,
    title="Time / domains",

    loc="upper left",

    bbox_to_anchor=(0.02, 0.55),

    fontsize=18,
    title_fontsize=20,

    framealpha=0.95
)

ax1.add_artist(legend_time)

plt.tight_layout()
plt.show()

# ============================================================
# FIGURE 2 — ZOOM
# ============================================================

fig2, ax2 = plt.subplots(figsize=(13, 7), dpi=140)

# Domain shading
ax2.axvspan(dial_start, dial_end, color=DOMAIN_COLORS["Dialysate"], alpha=0.25)
ax2.axvspan(cell_start, cell_end, color=DOMAIN_COLORS["Cell layer"], alpha=0.25)
ax2.axvspan(mem_start, mem_end, color=DOMAIN_COLORS["Membrane"], alpha=0.25)

zoom_y = []

# Curves
for z_label, data in datasets.items():

    color = Z_COLORS[z_label]

    ax2.plot(
        data["R"],
        data["c0"],
        linestyle="--",
        lw=3.5,
        color=color
    )

    ax2.plot(
        data["R"],
        data["c5"],
        linestyle="-",
        lw=3.5,
        color=color
    )

    ax2.plot(
        r_target,
        data["c0_val"],
        marker="o",
        ms=7,
        color=color
    )

    ax2.plot(
        r_target,
        data["c5_val"],
        marker="s",
        ms=7,
        color=color
    )

    mask = (data["R"] >= zoom_xmin) & (data["R"] <= zoom_xmax)

    zoom_y.extend(data["c0"][mask])
    zoom_y.extend(data["c5"][mask])

# Boundaries
for x in [1.5575, 1.5775]:
    ax2.axvline(x, color="gray", linestyle="--", lw=1.5)

# Limits
ax2.set_xlim(zoom_xmin, zoom_xmax)

ymin = min(zoom_y)
ymax = max(zoom_y)

ypad = 0.08 * (ymax - ymin)

ax2.set_ylim(ymin - ypad, ymax + ypad)

# ============================================================
# LABELS
# ============================================================

ax2.set_title(
    "Zoom near r = 1.5575 mm",
    fontsize=22,
    fontweight="bold"
)

ax2.set_xlabel(
    "Arc length (mm)",
    fontsize=20,
    fontweight="bold"
)

ax2.set_ylabel(
    "Molar concentration (mol/m³)",
    fontsize=20,
    fontweight="bold"
)

ax2.tick_params(axis="both", labelsize=17)

ax2.grid(alpha=0.3)

# ============================================================
# LEGENDS
# ============================================================

# BIG LEGEND 1: axial position
legend_zoom_1 = ax2.legend(
    handles=z_handles,
    title="Axial position",

    loc="upper right",

    fontsize=18,
    title_fontsize=20,

    framealpha=0.95
)

ax2.add_artist(legend_zoom_1)

# BIG LEGEND 2: line meaning
zoom_time_handles = [
    Line2D([0], [0], color="black", lw=4, linestyle="--", label="0 min"),
    Line2D([0], [0], color="black", lw=4, linestyle="-", label="t = 5 minutes"),
]

legend_zoom_2 = ax2.legend(
    handles=zoom_time_handles,

    title="Line / marker meaning",

    loc="lower right",

    fontsize=18,
    title_fontsize=20,

    framealpha=0.95
)

ax2.add_artist(legend_zoom_2)

plt.tight_layout()
plt.show()

# ============================================================
# PRINT VALUES
# ============================================================

print(f"\nConcentration values at r = {r_target:.4f} mm")

print("-" * 68)

print(
    f"{'Axial position':<14} "
    f"{'0 min':>16} "
    f"{'5 minutes':>22}"
)

print("-" * 68)

for z_label, data in datasets.items():

    print(
        f"{z_label:<14}"
        f"{data['c0_val']:>16.6f}"
        f"{data['c5_val']:>22.6f}"
    )

# ============================================================
# CONCENTRATION DIFFERENCE
# Difference = C(r = 1.8 mm) - C(r = 1.5775 mm)
# Only for z = 0.5 mm and z = 19.5 mm
# ============================================================

print("\nConcentration difference at 5 minutes")

print("Difference = C(r = 1.8 mm) - C(r = 1.5775 mm)")

print("-" * 90)

for z_label in ["z = 0.5 mm", "z = 19.5 mm"]:

    data = datasets[z_label]

    R = data["R"]

    c5 = data["c5"]

    c_r18 = concentration_at_r(R, c5, 1.8000)

    c_r15775 = concentration_at_r(R, c5, 1.5775)

    difference = c_r18 - c_r15775

    print(
        f"{z_label:<12} | "
        f"C(1.8 mm) = {c_r18:.6e} | "
        f"C(1.5775 mm) = {c_r15775:.6e} | "
        f"Difference = {difference:.6e}"
    )

