# -*- coding: utf-8 -*-
"""radial_profiles_static.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZQ0K2WNillW3I7xh69VXb1ABUAUKdMPh
"""

import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.patches import Patch

# ============================================================
# LOAD COMSOL FILE
# ============================================================

file = "radialconcentrationdistribution_baselineIO_z=10mm.txt"

df = pd.read_csv(
    file,
    comment="%",
    sep=r"\s+",
    header=None,
    engine="python"
)

df = df.sort_values(by=0).reset_index(drop=True)

R = df[0]

# Time columns
c0  = df[2]
c25 = df[7]
c5  = df[12]
c75 = df[17]
c10 = df[22]

# ============================================================
# DOMAIN DEFINITIONS
# ============================================================

blood_start, blood_end = 0.00, 0.15
mem_start, mem_end     = 0.15, 0.25
cell_start, cell_end   = 0.25, 0.27
dial_start, dial_end   = 0.27, 1.80

DOMAIN_COLORS = {
    "Dialysate": "#cfe8ff",
    "Cell": "#ffd9b3",
    "Membrane": "#f4c2c2",
    "Blood": "#d6f5d6",
}

TIME_COLORS = {
    "0 min":   "#00429d",
    "2.5 min": "#ff7f0e",
    "5 min":   "#9467bd",
    "7.5 min": "#ffcc00",
    "10 min":  "#000000",
}

# ============================================================
# PLOT
# ============================================================

fig, ax = plt.subplots(figsize=(14, 8), dpi=140)

# ============================================================
# DOMAIN SHADING
# ============================================================

ax.axvspan(blood_start, blood_end, color=DOMAIN_COLORS["Blood"], alpha=0.25)
ax.axvspan(mem_start, mem_end, color=DOMAIN_COLORS["Membrane"], alpha=0.25)
ax.axvspan(cell_start, cell_end, color=DOMAIN_COLORS["Cell"], alpha=0.25)
ax.axvspan(dial_start, dial_end, color=DOMAIN_COLORS["Dialysate"], alpha=0.25)

# ============================================================
# CONCENTRATION CURVES
# ============================================================

ax.plot(R, c0,  lw=4, color=TIME_COLORS["0 min"],   label="0 min")
ax.plot(R, c25, lw=4, color=TIME_COLORS["2.5 min"], label="2.5 min")
ax.plot(R, c5,  lw=4, color=TIME_COLORS["5 min"],   label="5 min")
ax.plot(R, c75, lw=4, color=TIME_COLORS["7.5 min"], label="7.5 min")
ax.plot(R, c10, lw=4, color=TIME_COLORS["10 min"],  label="10 min")

# ============================================================
# BOUNDARY LINES
# ============================================================

for x in [0.15, 0.25, 0.27]:
    ax.axvline(x, color="gray", linestyle="--", linewidth=1.5)

# ============================================================
# BIG LABELS
# ============================================================

ax.set_title(
    "Molar concentration profile (z = 10 mm)",
    fontsize=26,
    fontweight="bold"
)

ax.set_xlabel(
    "Arc length (mm)",
    fontsize=24,
    fontweight="bold"
)

ax.set_ylabel(
    "Molar concentration (mol/m³)",
    fontsize=24,
    fontweight="bold"
)

ax.tick_params(axis='both', labelsize=20)

ax.set_xlim(0, 1.8)

ax.grid(alpha=0.3)

# ============================================================
# BIG DOMAIN LEGEND (LEFT)
# ============================================================

domain_handles = [
    Patch(color=DOMAIN_COLORS["Blood"], label="Blood: 0–0.15 mm", alpha=0.4),
    Patch(color=DOMAIN_COLORS["Membrane"], label="Membrane: 0.15–0.25 mm", alpha=0.4),
    Patch(color=DOMAIN_COLORS["Cell"], label="Cell: 0.25–0.27 mm", alpha=0.4),
    Patch(color=DOMAIN_COLORS["Dialysate"], label="Dialysate: 0.27–1.80 mm", alpha=0.4),
    Line2D([0], [0], color="gray", linestyle="--", linewidth=1.5, label="Domain boundaries")
]

legend_domains = ax.legend(
    handles=domain_handles,

    title="Domains / ranges",

    # top middle-left
    loc="upper left",
    bbox_to_anchor=(0.18, 0.98),

    fontsize=20,
    title_fontsize=22,

    framealpha=0.95
)

ax.add_artist(legend_domains)

# ============================================================
# BIG TIME LEGEND (RIGHT OF DOMAIN LEGEND)
# ============================================================

legend_time = ax.legend(
    title="Time",

    # top middle-right
    loc="upper left",
    bbox_to_anchor=(0.67, 0.98),

    fontsize=20,
    title_fontsize=22,

    framealpha=0.95
)

ax.add_artist(legend_time)

plt.tight_layout(pad=1.5)

plt.show()

import re
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.patches import Patch

# ============================================================
# FOLDER WITH YOUR FILES
# ============================================================

DATA_FOLDER = Path(".")

# ============================================================
# DOMAIN DEFINITIONS
# ============================================================

DOMAINS = {
    "Dialysate": (0.00, 0.15),
    "Cell layer": (0.15, 0.17),
    "Membrane": (0.17, 0.27),
    "Blood lumen": (0.27, 1.80),
}

# ============================================================
# DISTINCT COLORS
# ============================================================

TIME_COLORS = {
    0.0:  "#00429d",
    0.5:  "#2ca02c",
    1.0:  "#d62728",
    2.5:  "#ff7f0e",
    5.0:  "#9467bd",
    10.0: "#000000",
}

TIMES = [0, 0.5, 1, 2.5, 5, 10]

# ============================================================
# DATA READER
# ============================================================

def read_comsol_txt(filepath):

    header_line = None
    data_lines = []

    with open(filepath) as f:
        for line in f:

            if line.startswith("%"):
                candidate = line.strip("%").strip()

                if candidate.startswith("r") and "@ t=" in candidate:
                    header_line = candidate
                continue

            data_lines.append(line.strip())

    columns = re.split(r"\s{2,}", header_line)

    rows = []
    for line in data_lines:
        parts = re.split(r"\s+", line)
        if len(parts) == len(columns):
            rows.append(parts)

    df = pd.DataFrame(rows, columns=columns).astype(float)

    time_map = {}

    for col in df.columns:
        match = re.search(r"@ t=([0-9.]+)", col)
        if match:
            t = float(match.group(1))
            time_map[t] = col

    df = df.sort_values("r")

    return df, time_map


# ============================================================
# DOMAIN SHADING
# ============================================================

def add_domains(ax):

    colors = {
        "Dialysate": "#cfe8ff",
        "Cell layer": "#ffd9b3",
        "Membrane": "#f4c2c2",
        "Blood lumen": "#d6f5d6",
    }

    for name, (x0, x1) in DOMAINS.items():
        ax.axvspan(x0, x1, color=colors[name], alpha=0.25)

    for x in [0.15, 0.17, 0.27]:
        ax.axvline(x, linestyle="--", color="gray", linewidth=1.5)


def domain_legend():

    return [
        Patch(color="#cfe8ff", label="Dialysate: 0–0.15 mm", alpha=0.4),
        Patch(color="#ffd9b3", label="Cell layer: 0.15–0.17 mm", alpha=0.4),
        Patch(color="#f4c2c2", label="Membrane: 0.17–0.27 mm", alpha=0.4),
        Patch(color="#d6f5d6", label="Blood lumen: 0.27–1.8 mm", alpha=0.4),
        Line2D([0], [0], color="gray", linestyle="--", linewidth=1.5, label="Domain boundaries")
    ]


# ============================================================
# PLOT FUNCTION
# ============================================================

def plot_file(filepath):

    df, time_map = read_comsol_txt(filepath)

    z = re.search(r'z=([0-9.]+)', filepath.name).group(1)

    fig, ax = plt.subplots(figsize=(13, 7), dpi=140)

    for t in TIMES:
        if t in time_map:
            ax.plot(
                df["r"],
                df[time_map[t]],
                color=TIME_COLORS[float(t)],
                linewidth=3.5,
                label=f"{t} min"
            )

    add_domains(ax)

    ax.set_title(
        f"Molar concentration profile (z = {z} mm)",
        fontsize=22,
        fontweight="bold"
    )

    ax.set_xlabel(
        "Arc length (mm)",
        fontsize=20,
        fontweight="bold"
    )

    ax.set_ylabel(
        "Molar concentration (mol/m³)",
        fontsize=20,
        fontweight="bold"
    )

    ax.tick_params(axis="both", labelsize=17)

    ax.set_xlim(0, 1.8)
    ax.grid(alpha=0.3)

    leg1 = ax.legend(
        title="Time",
        loc="upper right",
        fontsize=18,
        title_fontsize=20,
        framealpha=0.95
    )

    ax.add_artist(leg1)

    ax.legend(
        handles=domain_legend(),
        title="Domains / ranges",
        loc="center",
        bbox_to_anchor=(0.58, 0.35),
        fontsize=18,
        title_fontsize=20,
        framealpha=0.95
    )

    plt.tight_layout()

    save_name = f"concentration_profile_z{z}.png"
    plt.savefig(save_name, dpi=300)

    plt.show()


# ============================================================
# RUN ONLY FOR z = 10 mm
# ============================================================

file = DATA_FOLDER / "radialconcentrationdistribution_baselineOI_z=10mm.txt"

print("Plotting", file.name)
plot_file(file)

import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.patches import Patch

# ============================================================
# LOAD COMSOL FILE
# ============================================================

file = "radialconcentrationdistribution_baselineadjustedOI_z=10mm.txt"

df = pd.read_csv(
    file,
    comment="%",
    sep=r"\s+",
    header=None,
    engine="python"
)

df = df.sort_values(by=0).reset_index(drop=True)

R = df[0]

# Correct time columns
c0  = df[2]    # 0 min
c25 = df[7]    # 2.5 min
c5  = df[12]   # 5 min
c75 = df[17]   # 7.5 min
c10 = df[22]   # 10 min

# ============================================================
# DOMAIN DEFINITIONS
# ============================================================

dial_start, dial_end   = 0.0000, 1.5575
cell_start, cell_end   = 1.5575, 1.5775
mem_start, mem_end     = 1.5775, 1.6775
blood_start, blood_end = 1.6775, 1.8000

DOMAIN_COLORS = {
    "Dialysate": "#cfe8ff",
    "Cell": "#ffd9b3",
    "Membrane": "#f4c2c2",
    "Blood": "#d6f5d6",
}

TIME_COLORS = {
    "0 min":   "#00429d",
    "2.5 min": "#ff7f0e",
    "5 min":   "#9467bd",
    "7.5 min": "#ffcc00",
    "10 min":  "#000000",
}

# ============================================================
# PLOT
# ============================================================

fig, ax = plt.subplots(figsize=(14, 8), dpi=140)

ax.axvspan(dial_start, dial_end, color=DOMAIN_COLORS["Dialysate"], alpha=0.25)
ax.axvspan(cell_start, cell_end, color=DOMAIN_COLORS["Cell"], alpha=0.25)
ax.axvspan(mem_start, mem_end, color=DOMAIN_COLORS["Membrane"], alpha=0.25)
ax.axvspan(blood_start, blood_end, color=DOMAIN_COLORS["Blood"], alpha=0.25)

ax.plot(R, c0,  lw=4, color=TIME_COLORS["0 min"],   label="0 min")
ax.plot(R, c25, lw=4, color=TIME_COLORS["2.5 min"], label="2.5 min")
ax.plot(R, c5,  lw=4, color=TIME_COLORS["5 min"],   label="5 min")
ax.plot(R, c75, lw=4, color=TIME_COLORS["7.5 min"], label="7.5 min")
ax.plot(R, c10, lw=4, color=TIME_COLORS["10 min"],  label="10 min")

for x in [1.5575, 1.5775, 1.6775]:
    ax.axvline(x, color="gray", linestyle="--", linewidth=1.5)

ax.set_title("Molar concentration profile (z = 10 mm)", fontsize=26, fontweight="bold")
ax.set_xlabel("Arc length (mm)", fontsize=24, fontweight="bold")
ax.set_ylabel("Molar concentration (mol/m³)", fontsize=24, fontweight="bold")
ax.tick_params(axis="both", labelsize=20)
ax.set_xlim(0, 1.8)
ax.grid(alpha=0.3)

legend1 = ax.legend(
    title="Time",
    loc="upper left",
    bbox_to_anchor=(0.02, 0.98),
    fontsize=20,
    title_fontsize=22,
    frameon=True,
    framealpha=0.95
)

ax.add_artist(legend1)

domain_handles = [
    Patch(color=DOMAIN_COLORS["Dialysate"], label="Dialysate: 0–1.5575 mm", alpha=0.4),
    Patch(color=DOMAIN_COLORS["Cell"], label="Cell layer: 1.5575–1.5775 mm", alpha=0.4),
    Patch(color=DOMAIN_COLORS["Membrane"], label="Membrane: 1.5775–1.6775 mm", alpha=0.4),
    Patch(color=DOMAIN_COLORS["Blood"], label="Blood lumen: 1.6775–1.8000 mm", alpha=0.4),
    Line2D([0], [0], color="gray", linestyle="--", linewidth=1.5, label="Domain boundaries")
]

ax.legend(
    handles=domain_handles,
    title="Domains / ranges",
    loc="upper left",
    bbox_to_anchor=(0.24, 0.98),
    fontsize=20,
    title_fontsize=22,
    frameon=True,
    framealpha=0.95
)

plt.tight_layout(pad=1.5)
plt.show()

# ============================================================
# CONCENTRATION DIFFERENCE: BLOOD - MEMBRANE
# ============================================================

r_membrane = 1.5775
r_blood = 1.8

idx_membrane = (df[0] - r_membrane).abs().idxmin()
idx_blood = (df[0] - r_blood).abs().idxmin()

times = {
    "2.5 min": 7,
    "5 min": 12,
    "7.5 min": 17,
    "10 min": 22
}

print("\nConcentration difference:")
print("Δc = c(r=1.8 mm) - c(r=1.5775 mm)\n")

for label, col in times.items():
    c_membrane = df.loc[idx_membrane, col]
    c_blood = df.loc[idx_blood, col]
    delta_c = c_blood - c_membrane

    print(f"{label}:")
    print(f"  c(1.8 mm)      = {c_blood:.8f} mol/m³")
    print(f"  c(1.5775 mm)   = {c_membrane:.8f} mol/m³")
    print(f"  Δc             = {delta_c:.8f} mol/m³\n")