# -*- coding: utf-8 -*-
"""split_cell_layer_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ljgQT2Ahgzt2JKgUCjJmVVd3-03Kq62D
"""

from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Use the folder where your notebook/script is running
data_dir = Path(".")

configs = {
    "Inside-out": "totalnormalfluxCD_insideoutcountercurrent_splitcell_Km2_{}.txt",
    "outside-in": "totalnormalfluxCD_outsideincountercurrent_splitcell_Km2_{}.txt",
    "adjusted outside-in": "totalnormalfluxCD_adjustedoutsideincountercurrent_splitcell_Km2_{}.txt",
}

km_values = [5, 10, 15, 20]
baseline_km = 20

def read_final_flux(file_path):
    df = pd.read_csv(
        file_path,
        comment="%",
        sep=r"\s+",
        header=None,
        names=["time_min", "flux"]
    )
    return df.loc[df["time_min"].idxmax(), "flux"]

flux_data = {}

for config_name, filename_template in configs.items():
    flux_data[config_name] = {}

    for km in km_values:
        file_path = data_dir / filename_template.format(km)

        if not file_path.exists():
            raise FileNotFoundError(f"Missing file: {file_path}")

        flux_data[config_name][km] = read_final_flux(file_path)

relative_change = {}

for config_name, values in flux_data.items():
    baseline_flux = values[baseline_km]

    relative_change[config_name] = {
        km: ((values[km] - baseline_flux) / baseline_flux) * 100
        for km in km_values
    }

plot_df = pd.DataFrame(relative_change, index=km_values)

fig, ax = plt.subplots(figsize=(7.2, 4.6))

x = np.arange(len(km_values))
bar_width = 0.24

for i, config_name in enumerate(plot_df.columns):
    ax.bar(
        x + (i - 1) * bar_width,
        plot_df[config_name],
        width=bar_width,
        label=config_name
    )

ax.axhline(0, linewidth=1, linestyle="--")

ax.set_xticks(x)
ax.set_xticklabels(km_values)

ax.set_xlabel("Apical $K_m$ [µM]")
ax.set_ylabel("Δ Cell → Dialysate Flux [%]")
ax.set_title("Relative change in secretion into dialysate")

ax.legend(frameon=False)

y_min = plot_df.min().min()
y_max = plot_df.max().max()
padding = max((y_max - y_min) * 0.25, 0.001)
ax.set_ylim(y_min - padding, y_max + padding)

ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

plt.tight_layout()
plt.show()

print(plot_df)

from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ============================================================
# 1) CONSTANTS
# ============================================================

C_in = 0.1                 # mol/m^3
A_cm2 = 0.13               # membrane area in cm^2
A_m2 = A_cm2 * 1e-4        # convert cm^2 to m^2
mps_to_uL_min_cm2 = 6e6    # m/s to uL/(min*cm^2)

data_dir = Path(".")

# ============================================================
# 2) FILE TEMPLATES FOR THE 3 CONFIGURATIONS
# ============================================================

configs = {
    "Inside-out": "totalnormalfluxBM_insideoutcountercurrent_splitcell_Km2_{}.txt",
    "Outside-in": "totalnormalfluxBM_outsideincountercurrent_splitcell_Km2_{}.txt",
    "Adjusted outside-in": "totalnormalfluxBM_adjustedoutsideincountercurrent_splitcell_Km2_{}.txt",
}

km_values = [5, 10, 15, 20]
baseline_km = 20

# ============================================================
# 3) FUNCTIONS
# ============================================================

def read_flux_file(file_path):
    df = pd.read_csv(
        file_path,
        comment="%",
        sep=r"\s+",
        header=None,
        names=["time_min", "flux_mol_s"]
    )
    return df


def compute_model_derived_clearance(df):
    time_min = df["time_min"].to_numpy()
    flux_mol_s = df["flux_mol_s"].to_numpy()

    time_sec = time_min * 60.0

    total_mol = np.trapz(flux_mol_s, time_sec)

    CL_model_m_s = total_mol / (time_sec[-1] * A_m2 * C_in)

    CL_model_uL_min_cm2 = abs(CL_model_m_s * mps_to_uL_min_cm2)

    return CL_model_uL_min_cm2, total_mol

# ============================================================
# 4) COMPUTE CLEARANCE FOR EACH CONFIGURATION AND Km2
# ============================================================

clearance_data = {}
total_mol_data = {}

for config_name, filename_template in configs.items():
    clearance_data[config_name] = {}
    total_mol_data[config_name] = {}

    for km in km_values:
        file_path = data_dir / filename_template.format(km)

        if not file_path.exists():
            raise FileNotFoundError(f"Missing file: {file_path}")

        df = read_flux_file(file_path)

        clearance, total_mol = compute_model_derived_clearance(df)

        clearance_data[config_name][km] = clearance
        total_mol_data[config_name][km] = total_mol

# ============================================================
# 5) RELATIVE CHANGE VS Km2 = 20
# ============================================================

relative_change = {}

for config_name, values in clearance_data.items():
    baseline_clearance = values[baseline_km]

    relative_change[config_name] = {
        km: ((values[km] - baseline_clearance) / baseline_clearance) * 100
        for km in km_values
    }

clearance_df = pd.DataFrame(clearance_data, index=km_values)
relative_change_df = pd.DataFrame(relative_change, index=km_values)

# ============================================================
# 6) PLOT RELATIVE CLEARANCE CHANGE
# ============================================================

fig, ax = plt.subplots(figsize=(7.2, 4.6))

x = np.arange(len(km_values))
bar_width = 0.24

for i, config_name in enumerate(relative_change_df.columns):
    ax.bar(
        x + (i - 1) * bar_width,
        relative_change_df[config_name],
        width=bar_width,
        label=config_name
    )

ax.axhline(0, linewidth=1, linestyle="--")

ax.set_xticks(x)
ax.set_xticklabels(km_values)

ax.set_xlabel("Apical $K_m$ [µM]")
ax.set_ylabel("Δ end point time-average clearance [%]")
ax.set_title("Relative change in 'end point time-average clearance'")

ax.legend(frameon=False)

y_min = relative_change_df.min().min()
y_max = relative_change_df.max().max()
padding = max((y_max - y_min) * 0.25, 0.001)
ax.set_ylim(y_min - padding, y_max + padding)

ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

plt.tight_layout()
plt.show()

# ============================================================
# 7) PRINT TABLES
# ============================================================

print("\nAbsolute model-derived clearance [uL/(min*cm^2)]:")
print(clearance_df)

print("\nRelative change vs Km2 = 20 [%]:")
print(relative_change_df)

