# -*- coding: utf-8 -*-
"""velocity_and_pressure_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EQcKAXCIemH7yi-gl427SH97ut7VUoDE
"""

import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter

file_path = "velocity_baselineinsideout.txt"

# Read COMSOL text file; lines beginning with % are comments
df = pd.read_csv(
    file_path,
    comment="%",
    sep=r"\s+",
    header=None
)

# Columns: R, Z, then velocity w at t=0, 20, ..., 240
df.columns = ["R", "Z"] + [f"w_t{t}" for t in range(0, 241, 20)]

# Reproduce shown plot: valid inside-radius values, using t=0
plot_df = df[["R", "w_t0"]].dropna()
plot_df = plot_df[plot_df["R"] <= 0.15]
plot_df = plot_df.sort_values("R")

fig, ax = plt.subplots(figsize=(9.2, 4.0))

ax.plot(plot_df["R"], plot_df["w_t0"], color="orange", linewidth=1.2)

# Bigger title and axis labels
ax.set_title("Velocity field, z-component (m/s)", fontsize=20)
ax.set_xlabel("Arc length (mm)", fontsize=18)
ax.set_ylabel("Velocity field (m/s)", fontsize=18)

# Bigger tick labels
ax.tick_params(axis='both', labelsize=16)

ax.set_xlim(-0.003, 0.153)
ax.set_ylim(-0.003, 0.05)

ax.set_xticks([0, 0.02, 0.04, 0.06, 0.08, 0.1, 0.12, 0.14])
ax.set_yticks([i / 1000 for i in range(0, 51, 5)])

ax.xaxis.set_major_formatter(FuncFormatter(lambda x, pos: f"{x:g}"))
ax.yaxis.set_major_formatter(FuncFormatter(lambda y, pos: f"{y:g}"))

ax.grid(True, color="#d9d9d9", linewidth=1, alpha=0.7)

plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter

file_path = "velocity_baselineoutsidein.txt"

# Read COMSOL text file
df = pd.read_csv(
    file_path,
    comment="%",
    sep=r"\s+",
    header=None
)

# Assign column names
df.columns = ["R", "Z"] + [f"w_t{t}" for t in range(0, 241, 20)]

# Keep valid data only
plot_df = df[["R", "w_t0"]].dropna()
plot_df = plot_df.sort_values("R")

# Create figure
fig, ax = plt.subplots(figsize=(10, 4))

# Plot line
ax.plot(
    plot_df["R"],
    plot_df["w_t0"],
    color="orange",
    linewidth=2
)

# Titles and labels
ax.set_title(
    "Velocity field, z-component (m/s)",
    fontsize=18,
    pad=10
)

ax.set_xlabel(
    "Arc length (mm)",
    fontsize=16
)

ax.set_ylabel(
    "Velocity field, z-component (m/s)",
    fontsize=16
)

# Bigger ticks
ax.tick_params(axis='both', labelsize=13)

# Set tighter y-limits to remove whitespace
ax.set_ylim(
    0,
    plot_df["w_t0"].max() * 1.05
)

# Domain boundaries
boundaries = [0.15, 0.17, 0.27]

for x in boundaries:
    ax.axvline(
        x=x,
        color="gray",
        linestyle="--",
        linewidth=2
    )



# Domain description box OUTSIDE plot
domain_text = (
    "Domains / ranges\n"
    "Dialysate: 0–0.15 mm\n"
    "Cell layer: 0.15–0.17 mm\n"
    "Membrane: 0.17–0.27 mm\n"
    "Blood lumen: 0.27–1.8 mm\n"
    "------ Domain boundaries"
)

ax.text(
    1.02,
    0.5,
    domain_text,
    transform=ax.transAxes,
    fontsize=11,
    va="center",
    ha="left",
    bbox=dict(
        facecolor="white",
        edgecolor="lightgray",
        boxstyle="round,pad=0.5",
        alpha=0.95
    )
)

# Formatting
ax.xaxis.set_major_formatter(
    FuncFormatter(lambda x, pos: f"{x:g}")
)

ax.yaxis.set_major_formatter(
    FuncFormatter(lambda y, pos: f"{y:g}")
)

# Grid
ax.grid(
    True,
    color="#d9d9d9",
    linewidth=1,
    alpha=0.7
)

# Layout
plt.tight_layout()

# Save figure
plt.savefig(
    "velocity_profile_clean.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter

# =========================
# SELECT FILE
# =========================
file_path = "pressure_baselineoutsidein.txt"
# file_path = "pressure_baselineinsideout.txt"

# =========================
# READ COMSOL FILE
# =========================
df = pd.read_csv(
    file_path,
    comment="%",
    sep=r"\s+",
    header=None
)

# Create column names
# First 2 columns = R/Z
# Remaining columns = pressure at different times
ncols = df.shape[1]

time_columns = [f"p_t{i}" for i in range(ncols - 2)]

df.columns = ["R", "Z"] + time_columns

# =========================
# USE PRESSURE AT t = 0
# =========================
plot_df = df[["Z", "p_t0"]].dropna()

# Sort by axial coordinate
plot_df = plot_df.sort_values("Z")

# Shift Z so arc length starts at 0
plot_df["ArcLength"] = plot_df["Z"] - plot_df["Z"].min()

# =========================
# CREATE FIGURE
# =========================
fig, ax = plt.subplots(figsize=(12, 6))

# Plot
ax.plot(
    plot_df["ArcLength"],
    plot_df["p_t0"],
    color="#5b4b3a",
    linewidth=2
)

# =========================
# TITLES & LABELS
# =========================
ax.set_title(
    "Pressure (Pa)",
    fontsize=24
)

ax.set_xlabel(
    "Arc length (mm)",
    fontsize=20
)

ax.set_ylabel(
    "Pressure (Pa)",
    fontsize=20
)

# Bigger ticks
ax.tick_params(
    axis='both',
    labelsize=16
)


# =========================
# GRID & FORMATTING
# =========================
ax.grid(
    True,
    color="#d9d9d9",
    linewidth=1,
    alpha=0.7
)

ax.xaxis.set_major_formatter(
    FuncFormatter(lambda x, pos: f"{x:g}")
)

ax.yaxis.set_major_formatter(
    FuncFormatter(lambda y, pos: f"{y:g}")
)

plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter

# =========================
# SELECT FILE
# =========================

file_path = "pressure_baselineinsideout.txt"

# =========================
# READ COMSOL FILE
# =========================
df = pd.read_csv(
    file_path,
    comment="%",
    sep=r"\s+",
    header=None
)

# Create column names
# First 2 columns = R/Z
# Remaining columns = pressure at different times
ncols = df.shape[1]

time_columns = [f"p_t{i}" for i in range(ncols - 2)]

df.columns = ["R", "Z"] + time_columns

# =========================
# USE PRESSURE AT t = 0
# =========================
plot_df = df[["Z", "p_t0"]].dropna()

# Sort by axial coordinate
plot_df = plot_df.sort_values("Z")

# Shift Z so arc length starts at 0
plot_df["ArcLength"] = plot_df["Z"] - plot_df["Z"].min()

# =========================
# CREATE FIGURE
# =========================
fig, ax = plt.subplots(figsize=(12, 6))

# Plot
ax.plot(
    plot_df["ArcLength"],
    plot_df["p_t0"],
    color="#5b4b3a",
    linewidth=2
)

# =========================
# TITLES & LABELS
# =========================
ax.set_title(
    "Pressure (Pa)",
    fontsize=24
)

ax.set_xlabel(
    "Arc length (mm)",
    fontsize=20
)

ax.set_ylabel(
    "Pressure (Pa)",
    fontsize=20
)

# Bigger ticks
ax.tick_params(
    axis='both',
    labelsize=16
)


# =========================
# GRID & FORMATTING
# =========================
ax.grid(
    True,
    color="#d9d9d9",
    linewidth=1,
    alpha=0.7
)

ax.xaxis.set_major_formatter(
    FuncFormatter(lambda x, pos: f"{x:g}")
)

ax.yaxis.set_major_formatter(
    FuncFormatter(lambda y, pos: f"{y:g}")
)

plt.tight_layout()
plt.show()

